In [1]:
# https://deepage.net/features/numpy-numpy.html

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a*3

array([3, 6, 9])

In [5]:
a+2

array([3, 4, 5])

In [6]:
# https://deepage.net/features/numpy-math.html -> numpy 수학함수/정수 정리

In [7]:
b = np.array([2,2,0])

In [8]:
a + b

array([3, 4, 3])

In [9]:
a / b

/Users/kobi.kuma/py3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 0.5,  1. ,  inf])

In [10]:
a * b

array([2, 4, 0])

In [12]:
np.dot(a,b) # inner product (a1,a2,a3) dot (b1, b2, b3) --> (a1*b1+a2*b2+a3*b3)

6

In [13]:
# https://deepage.net/features/numpy-dot.html -> 내적/곱셈

### 다양한 배열

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(0, 10, 15) # 15등분, 간격 수열

array([  0.        ,   0.71428571,   1.42857143,   2.14285714,
         2.85714286,   3.57142857,   4.28571429,   5.        ,
         5.71428571,   6.42857143,   7.14285714,   7.85714286,
         8.57142857,   9.28571429,  10.        ])

In [22]:
c = np.array([[1,2,3], [4,5,6]])

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
c.shape

(2, 3)

In [25]:
d = np.array([[ [1,2,3], [4,5,6], [7,8,9], [10,11,12]],
             [[13,14,15],[15,16,17],[18,19,20],[21,22,23]]])

In [26]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [29]:
d.shape # 4x3 * 2

(2, 4, 3)

In [30]:
# https://deepage.net/features/numpy-shape.html -> shape

In [31]:
np.sum(c)

21

In [32]:
np.sum(c,axis=1) # axis(축)

array([ 6, 15])

In [34]:
np.sum(c,axis=0) 

array([5, 7, 9])

In [35]:
# https://deepage.net/features/numpy-axis.html -> 축과 차수

In [36]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [38]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
## random

In [43]:
np.random.randn() # from normal-distribution

-1.366142689708338

In [44]:
np.random.rand() # 0~1

0.5468638468549317

In [45]:
np.random.randn(2,3)

array([[ 1.28857445,  0.24346543,  0.95596268],
       [ 1.51247157, -1.16417621,  1.73849257]])

In [46]:
## index / slicing

In [47]:
a

array([1, 2, 3])

In [48]:
a[0]

1

In [49]:
a[1]

2

In [50]:
a[1] = 3

In [51]:
a

array([1, 3, 3])

In [52]:
a[1] = 2

In [53]:
a

array([1, 2, 3])

In [54]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
c[0,0]

1

In [56]:
c[0,2]

3

In [57]:
c[1,2]

6

In [58]:
d = np.array([0,5,2,7,1,9])

In [59]:
d[1:5]

array([5, 2, 7, 1])

In [61]:
d[1:3] # start_point:finish_point (not includ finish_point)

array([5, 2])

In [64]:
d[0:5:2] # sp:fp:interval

array([0, 2, 1])

In [66]:
d[::-1] # reverse

array([9, 1, 7, 2, 5, 0])

In [67]:
a

array([1, 2, 3])

In [68]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a+c

array([[2, 4, 6],
       [5, 7, 9]])

In [70]:
a*c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

## numpy high-speed operation

In [71]:
import numpy as np
import time

In [72]:
def calculate_time():
    a = np.random.randn(100000)
    b = [a]
    st = time.time()
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("numpy time\t%f sec" % (time.time()-st))
    st = time.time()
    for _ in range(1000):
        sum_2 = sum(b)
    print("not used numpy time\t%f sec" %(time.time()-st))


In [73]:
calculate_time()

numpy time	0.039813 sec
not used numpy time	0.059259 sec


In [74]:
timeit np.sum(a)

2.7 µs ± 64.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
timeit sum(a)

1.13 µs ± 15.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
