In [1]:
# https://deepage.net/features/numpy-slicing.html

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5]
a[1:-1]

[2, 3, 4]

In [4]:
a[1:3]

[2, 3]

### 사용법
* `start:stop:step` 
* start : 시작점
* stop : 종점
* step : 단위
![image](https://deepage.net/img/numpy/slicing/slicing.jpg)

In [5]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a[5:11:2]

array([5, 7, 9])

In [7]:
a[1:5:2]

array([1, 3])

In [8]:
a[5:-1:2]

array([ 5,  7,  9, 11, 13])

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[1:5]

array([1, 2, 3, 4])

In [11]:
a[2:8:2]

array([2, 4, 6])

In [12]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
a[:3]

array([0, 1, 2])

In [14]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [15]:
a[:3], a[3:]

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [16]:
a[::2]

array([0, 2, 4, 6, 8])

In [17]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 다차원
`,`로 구분 `[:,:,:]`

In [18]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
b[1:3,2:4] # y:1,x:3 , y:2,x:4

array([[ 7,  8],
       [12, 13]])

In [22]:
b[:2, 1:] # -x:2 , y:1-

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [23]:
b[::2, :] # y_step 2,all

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [24]:
b[:, ::2] # all, x_setp 2

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [25]:
b[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [27]:
b[::-1, ::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

### 3차원

In [28]:
c = np.zeros((3,4,5))
c

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [29]:
c[1:, 1:4,:] = 1
c

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [30]:
c[:,1:2,3:] = 2
c

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  2.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  2.,  2.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  2.,  2.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [31]:
c[:,:,::2] = 3

In [32]:
c

array([[[ 3.,  0.,  3.,  0.,  3.],
        [ 3.,  0.,  3.,  2.,  3.],
        [ 3.,  0.,  3.,  0.,  3.],
        [ 3.,  0.,  3.,  0.,  3.]],

       [[ 3.,  0.,  3.,  0.,  3.],
        [ 3.,  1.,  3.,  2.,  3.],
        [ 3.,  1.,  3.,  1.,  3.],
        [ 3.,  1.,  3.,  1.,  3.]],

       [[ 3.,  0.,  3.,  0.,  3.],
        [ 3.,  1.,  3.,  2.,  3.],
        [ 3.,  1.,  3.,  1.,  3.],
        [ 3.,  1.,  3.,  1.,  3.]]])

In [33]:
c[::2,::2, ::2]=4
c

array([[[ 4.,  0.,  4.,  0.,  4.],
        [ 3.,  0.,  3.,  2.,  3.],
        [ 4.,  0.,  4.,  0.,  4.],
        [ 3.,  0.,  3.,  0.,  3.]],

       [[ 3.,  0.,  3.,  0.,  3.],
        [ 3.,  1.,  3.,  2.,  3.],
        [ 3.,  1.,  3.,  1.,  3.],
        [ 3.,  1.,  3.,  1.,  3.]],

       [[ 4.,  0.,  4.,  0.,  4.],
        [ 3.,  1.,  3.,  2.,  3.],
        [ 4.,  1.,  4.,  1.,  4.],
        [ 3.,  1.,  3.,  1.,  3.]]])