In [3]:
# 1.2.5 numpy-dtype

* `dtype` : 데이터형 표현
* 내부적으로는 C로 구현되어 있기 때문에, 데이터형을 지정하면 메모리/실행에 효율적일 수 있음

### Data Types
#### Int
* int8 / int16/ int32/ int64

#### uint
* uint8 / uint16 / uint32 / uint64

#### float
* float16/float32/float64/float128

#### bool
* bool


In [4]:
import numpy as np

In [5]:
a = np.array([0, 1, 2])

In [6]:
a.dtype

dtype('int64')

In [7]:
b = np.array([0, 1, 2], dtype='int32')

In [8]:
b.dtype

dtype('int32')

In [9]:
c = np.array([0,1,2], dtype='float')
c.dtype

dtype('float64')

In [10]:
d = np.array([3e50, 4e45], dtype='int64')

OverflowError: Python int too large to convert to C long

In [11]:
d = np.array([3e50, 4e45], dtype='float64')

In [12]:
d.dtype

dtype('float64')

In [13]:
e = np.array([3.5, 4.2, -4.3], dtype = 'int')

In [14]:
e

array([ 3,  4, -4])

In [15]:
f = np.array([0, 3, 0, -1], dtype='bool')
f

array([False,  True, False,  True], dtype=bool)

### casting

In [16]:
g = np.array([0., 1., 2.], dtype='int64')
g

array([0, 1, 2])

In [17]:
g.dtype

dtype('int64')

In [18]:
g.dtype = 'int32'

In [19]:
g.dtype

dtype('int32')

In [20]:
g

array([0, 0, 1, 0, 2, 0], dtype=int32)

In [21]:
g.dtype = 'float64'
g

array([  0.00000000e+000,   4.94065646e-324,   9.88131292e-324])

In [22]:
g.dtype = 'float32'
g

array([  0.00000000e+00,   0.00000000e+00,   1.40129846e-45,
         0.00000000e+00,   2.80259693e-45,   0.00000000e+00], dtype=float32)

In [23]:
g.dtype = 'int'
g

array([0, 1, 2])

## size

In [24]:
h = np.random.randint(10, size=100, dtype='int8')
i = np.random.randint(10, size=100, dtype='int64')

In [25]:
h.nbytes

100

In [26]:
i.nbytes

800

In [27]:
h

array([7, 5, 2, 3, 6, 5, 4, 9, 0, 3, 4, 6, 2, 1, 2, 3, 5, 8, 1, 6, 9, 7, 2,
       4, 8, 9, 0, 2, 8, 0, 7, 5, 3, 8, 6, 1, 5, 1, 1, 2, 9, 6, 3, 7, 5, 3,
       6, 7, 5, 1, 3, 4, 8, 4, 0, 2, 7, 6, 5, 3, 1, 1, 0, 2, 2, 0, 9, 1, 1,
       6, 2, 8, 8, 8, 0, 5, 0, 2, 8, 2, 8, 7, 7, 1, 7, 8, 6, 6, 9, 0, 4, 8,
       3, 5, 6, 6, 0, 2, 0, 1], dtype=int8)

In [28]:
i

array([1, 4, 9, 4, 6, 9, 2, 0, 6, 7, 5, 0, 2, 3, 6, 6, 0, 4, 1, 3, 4, 8, 0,
       3, 5, 4, 9, 2, 3, 3, 4, 3, 6, 4, 6, 1, 4, 1, 0, 0, 1, 3, 7, 1, 4, 5,
       8, 8, 3, 5, 0, 3, 5, 9, 5, 9, 6, 4, 2, 4, 9, 4, 6, 8, 9, 6, 2, 2, 5,
       8, 1, 8, 8, 5, 3, 4, 8, 3, 4, 1, 0, 0, 8, 6, 2, 7, 0, 2, 6, 9, 5, 6,
       7, 0, 3, 2, 7, 2, 6, 5])

In [29]:
# int8 -> 1byte , int64 -> 8byte