### ndim (차원수?)
* shape으로 확인 가능

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim

2

### axis
* ![img](https://deepage.net/img/numpy/axis/numpy-shape-2d.jpg)

In [5]:
a = np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
a.shape

(3, 2)

In [7]:
a.ndim

2

In [8]:
b = np.array([a, a])
b.shape

(2, 3, 2)

In [9]:
b

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [10]:
b.ndim

3

![img](https://deepage.net/img/numpy/axis/numpy-shape-3d.jpg)

In [11]:
b.sum(axis=0).shape

(3, 2)

In [12]:
b.sum(axis=1).shape

(2, 2)

In [13]:
b.sum(axis=2).shape

(2, 3)

In [14]:
b.sum(axis=2)

array([[1, 5, 9],
       [1, 5, 9]])

In [15]:
b.sum(axis=1)

array([[6, 9],
       [6, 9]])

In [16]:
b.sum(axis=0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])