In [1]:
# https://deepage.net/features/numpy-ndarray.html

In [2]:
# ndarray is (usually fixed-size) multi-dimentional container of items of the same type and size

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array([[1,2,3], [4,5,6]])

In [7]:
a

array([1, 2, 3])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
a.T

array([1, 2, 3])

In [11]:
a.data

In [12]:
a.dtype

dtype('int64')

In [13]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [14]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [15]:
a.flat[1]

2

In [16]:
b.flat[4]

5

In [17]:
c = np.array([1.-2.6j, 2.1+3.J, 4.-3.2j])

In [18]:
c.real

array([ 1. ,  2.1,  4. ])

In [19]:
c.imag

array([-2.6,  3. , -3.2])

In [20]:
c.dtype

dtype('complex128')

In [21]:
a.size, b.size, c.size

(3, 6, 3)

In [22]:
a.itemsize, b.itemsize, c.itemsize

(8, 8, 16)

In [23]:
a.nbytes, b.nbytes, c.nbytes

(24, 48, 48)

In [24]:
a.size * a.itemsize == a.nbytes

True

In [25]:
a.ndim, b.ndim

(1, 2)

In [26]:
a.shape, b.shape

((3,), (2, 3))

In [27]:
d = np.array([[[2,3,2], [2,2,2]], [[4,3,2],[5,7,1]]])

In [28]:
d.shape, d.ndim

((2, 2, 3), 3)

In [30]:
a.strides , b.strides, c.strides, d.strides

((8,), (24, 8), (16,), (48, 24, 8))

In [31]:
a.ctypes.data

140279572442240

In [32]:
a.base

In [33]:
e = a[:2]

In [34]:
e

array([1, 2])

In [35]:
e.base

array([1, 2, 3])

In [36]:
e.base is a

True