In [1]:
# https://deepage.net/features/numpy-copyview.html

* `copy` : 다른 메모리를 사용하고, 같은 요소 (object copy)
* `view` : 같은 메모리를 사용하고, 참조함 (reference)

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
d = a.view()

In [4]:
a

array([1, 2, 3])

In [5]:
d

array([1, 2, 3])

In [6]:
d[0] = 100

In [7]:
a

array([100,   2,   3])

In [8]:
d

array([100,   2,   3])

In [9]:
c = a.copy()

In [10]:
c[1] = 25

In [11]:
c

array([100,  25,   3])

In [12]:
a

array([100,   2,   3])

## 연산에서의 차이
* copy , view에 따라 연산 종류가 다를 수 있음

In [13]:
# assgin
a = np.array([1,2,3])
b = a

In [14]:
id(a) == id(b)

True

In [15]:
c = a[:]

In [16]:
id(a) == id(c)

False

In [19]:
c[1] = 22

In [21]:
a  #  c = a[:] --> view

array([ 1, 22,  3])

In [22]:
d = a[:1]

In [23]:
d

array([1])

In [24]:
d[0] = 11

In [25]:
a

array([11, 22,  3])

In [26]:
d

array([11])

In [27]:
## copy
e = a.copy()
e.base is a

False

In [28]:
e[2] = 234
e

array([ 11,  22, 234])

In [29]:
a

array([11, 22,  3])

In [30]:
print(a.base)

None


In [31]:
print(e.base)

None


In [32]:
print(d.base)

[11 22  3]


In [33]:
d.base is a

True

In [34]:
## operation

In [44]:
a = np.array([1,2,3])
c = a # c is a view
id(a), id(c)

(4572190880, 4572190880)

In [49]:
a = a + 1  # a.copy() + 1

In [50]:
a

array([3, 4, 5])

In [51]:
c # not effect

array([1, 2, 3])

In [52]:
id(a), id(c)

(4572192160, 4572190880)

In [53]:
a = np.array([1,2,3])

In [54]:
c = a

In [55]:
a += 1

In [56]:
c, a

(array([2, 3, 4]), array([2, 3, 4]))

In [57]:
print(id(c), id(a))

4572201248 4572201248


In [58]:
## np.add / np.subtract

In [59]:
a = np.array([1,2,3])
c = a

In [60]:
np.add(a,1,out=a)

array([2, 3, 4])

In [61]:
a, c

(array([2, 3, 4]), array([2, 3, 4]))

In [62]:
np.subtract(a, 1, out=a)

array([1, 2, 3])

In [63]:
a, c

(array([1, 2, 3]), array([1, 2, 3]))

In [64]:
## speed for A = X*4 + Y*3

In [65]:
def test():
    import time
    X = np.ones(100000000, dtype='int8')
    Y = np.ones(100000000, dtype='int8')
    a = time.time()
    for _ in range(100):
        X = X*4 + Y*3
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('X = X*4+Y*3 : {} sec'.format( (b-a)/100))
    
    a = time.time()
    for _ in range(100):
        X *=4
        X += Y*3
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('X*=4; X+=Y*3 : {} sec'.format( (b-a)/100))
    
    a = time.time()
    for _ in range(100):
        np.multiply(X, 4, out=X)
        np.multiply(Y, 3, out=Y)
        np.add(X, Y, out=X)
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('using function: {} sec'.format( (b-a)/100))
    

In [66]:
test()

X = X*4+Y*3 : 0.12069614171981811 sec
X*=4; X+=Y*3 : 0.09461004972457886 sec
using function: 0.06812822818756104 sec


In [72]:
## flatten
# flatten : copy & return reference
# ravel : return original memory location & view

In [68]:
a = np.random.randn(2,3,9)
b = a.ravel()
c = a.flatten()

In [69]:
a

array([[[-0.10337486,  0.78934166,  0.37356293,  0.56550298,  0.22879633,
          0.88990673, -0.42175703,  1.51514726,  1.22643986],
        [-0.04496767,  1.41659548,  0.51804519,  0.56610583,  0.44325043,
         -2.50822639,  1.07257303, -0.22414252, -0.35722473],
        [ 0.10563302, -1.31647792,  1.04181365, -0.37726385,  0.65073354,
         -0.12965029, -0.34888086,  1.56653478,  1.85730595]],

       [[-1.46669656,  0.09417404,  0.79085048, -1.5145402 , -0.70284417,
         -0.46263262, -0.57932253, -0.48260415,  0.13169651],
        [-1.35440393, -1.81313945, -0.48142038,  0.0696715 ,  1.87101777,
         -0.70982845, -0.11315134, -1.23749764,  2.97712608],
        [ 0.54687181, -1.07449273,  0.60945535,  0.62951775, -0.10549159,
          0.54767517, -0.87741215, -0.01102367,  0.65831477]]])

In [70]:
b

array([-0.10337486,  0.78934166,  0.37356293,  0.56550298,  0.22879633,
        0.88990673, -0.42175703,  1.51514726,  1.22643986, -0.04496767,
        1.41659548,  0.51804519,  0.56610583,  0.44325043, -2.50822639,
        1.07257303, -0.22414252, -0.35722473,  0.10563302, -1.31647792,
        1.04181365, -0.37726385,  0.65073354, -0.12965029, -0.34888086,
        1.56653478,  1.85730595, -1.46669656,  0.09417404,  0.79085048,
       -1.5145402 , -0.70284417, -0.46263262, -0.57932253, -0.48260415,
        0.13169651, -1.35440393, -1.81313945, -0.48142038,  0.0696715 ,
        1.87101777, -0.70982845, -0.11315134, -1.23749764,  2.97712608,
        0.54687181, -1.07449273,  0.60945535,  0.62951775, -0.10549159,
        0.54767517, -0.87741215, -0.01102367,  0.65831477])

In [71]:
c

array([-0.10337486,  0.78934166,  0.37356293,  0.56550298,  0.22879633,
        0.88990673, -0.42175703,  1.51514726,  1.22643986, -0.04496767,
        1.41659548,  0.51804519,  0.56610583,  0.44325043, -2.50822639,
        1.07257303, -0.22414252, -0.35722473,  0.10563302, -1.31647792,
        1.04181365, -0.37726385,  0.65073354, -0.12965029, -0.34888086,
        1.56653478,  1.85730595, -1.46669656,  0.09417404,  0.79085048,
       -1.5145402 , -0.70284417, -0.46263262, -0.57932253, -0.48260415,
        0.13169651, -1.35440393, -1.81313945, -0.48142038,  0.0696715 ,
        1.87101777, -0.70982845, -0.11315134, -1.23749764,  2.97712608,
        0.54687181, -1.07449273,  0.60945535,  0.62951775, -0.10549159,
        0.54767517, -0.87741215, -0.01102367,  0.65831477])

In [73]:
a[0,0,0] = 129

In [74]:
a[0,0,0], b[0], c[0]

(129.0, 129.0, -0.10337486489297826)

In [75]:
## fancy indexing : copy 

In [76]:
a = np.random.randint(10, size=100)

In [77]:
a

array([9, 0, 5, 7, 8, 2, 5, 1, 9, 7, 6, 9, 4, 2, 0, 7, 0, 1, 4, 2, 4, 8, 7,
       0, 1, 0, 2, 4, 3, 5, 2, 2, 5, 5, 4, 9, 7, 7, 6, 6, 3, 2, 3, 3, 2, 9,
       6, 2, 4, 4, 3, 7, 3, 1, 0, 0, 9, 0, 5, 8, 3, 9, 8, 5, 4, 0, 4, 3, 4,
       1, 7, 6, 2, 5, 7, 2, 7, 9, 6, 3, 4, 7, 8, 3, 8, 2, 0, 6, 8, 5, 5, 2,
       6, 5, 4, 1, 6, 7, 3, 3])

In [78]:
n = a % 3 == 0
n

array([ True,  True, False, False, False, False, False, False,  True,
       False,  True,  True, False, False,  True, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False, False,  True, False,  True, False,
        True,  True,  True,  True, False, False,  True,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False, False, False, False, False,  True,  True,  True, False,
       False, False,  True, False, False,  True,  True, False, False,
       False, False,  True, False, False, False,  True, False,  True,  True], dtype=bool)

In [79]:
a[n] # 3의 배수만 

array([9, 0, 9, 6, 9, 0, 0, 0, 0, 3, 9, 6, 6, 3, 3, 3, 9, 6, 3, 3, 0, 0, 9,
       0, 3, 9, 0, 3, 6, 9, 6, 3, 3, 0, 6, 6, 6, 3, 3])

In [84]:
k = a[n] ## copy instance

In [85]:
np.may_share_memory(a,k)

False

In [86]:
f = a[np.arange(0,10,2)]

In [87]:
np.may_share_memory(a,f)

False

In [88]:
## checking copy or view --> may_share_memory

In [89]:
a = np.array([1,2,3])
b = a
c = b
d = a.copy()

In [90]:
np.may_share_memory(a, b)

True

In [91]:
np.may_share_memory(a,c)

True

In [92]:
np.may_share_memory(a,d)

False

In [93]:
np.shares_memory(a,b)

True

In [94]:
np.shares_memory(a,d)

False