In [2]:
# https://deepage.net/features/numpy-broadcasting.html
# https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/

### `broadcasting`
* numpy의 용어로서, 다른 차원(모양)의 배열들 사이의 수학적 연산을 수행하는 기능
* ![image](https://eli.thegreenplace.net/images/2015/cal-data.png)

In [3]:
import numpy as np

In [5]:
macros = np.array([
    [0.3, 2.5, 3.5],
    [2.9, 27.5, 0],
    [0.4, 1.3, 23.9],
    [14.4, 6, 2.3]
])

In [7]:
result = np.zeros_like(macros)
print(result)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
cal_per_macro = np.array([9,4,4])

In [11]:
for i in range(macros.shape[0]):
    result[i,:] = macros[i, :] * cal_per_macro

In [12]:
result

array([[   2.7,   10. ,   14. ],
       [  26.1,  110. ,    0. ],
       [   3.6,    5.2,   95.6],
       [ 129.6,   24. ,    9.2]])

In [13]:
cal_per_macro_stretch = np.tile(cal_per_macro, (macros.shape[0], 1))
cal_per_macro_stretch

array([[9, 4, 4],
       [9, 4, 4],
       [9, 4, 4],
       [9, 4, 4]])

In [14]:
macros * cal_per_macro_stretch

array([[   2.7,   10. ,   14. ],
       [  26.1,  110. ,    0. ],
       [   3.6,    5.2,   95.6],
       [ 129.6,   24. ,    9.2]])

In [15]:
###

In [16]:
macros * cal_per_macro

array([[   2.7,   10. ,   14. ],
       [  26.1,  110. ,    0. ],
       [   3.6,    5.2,   95.6],
       [ 129.6,   24. ,    9.2]])

### Rule 1. ndim이 다를때는 shape의 선두에 1을 넣는다.

In [17]:
a = np.array([[1,2]])
a.shape

(1, 2)

In [18]:
b = np.array([3,4])
b.shape

(2,)

In [20]:
a + b # [3,4] --> [[3,4]]

array([[4, 6]])

### Rule 2. max or 1

```
(1, 3) <> (2,4,3)
-> (1, 1, 3) <> (2,4,3)
(1,) <> (2,4,3)
-> (1,1) <> (2,4,3)
-> (1,1,1) <> (2,4,3)
```


### Rule 3. 가장 많은 수에 맞춘다
```
(1,1,3) (4,2,1)
-> (4,2,3)
```

### Rule4. 요소 수는 1로 되어있는 차원 축의 값은 모두 같은 것으로 반복한다.
![image](https://deepage.net/img/numpy/broadcasting/broadcast-procedure.jpg)

In [23]:
a = np.array([1,2])
b = np.array([[3,4],[2,3]])
print(a)
print(b)

[1 2]
[[3 4]
 [2 3]]


In [24]:
a.shape, b.shape

((2,), (2, 2))

In [25]:
a+b, (a+b).shape

(array([[4, 6],
        [3, 5]]), (2, 2))

In [27]:
## 3dim
a = np.array([[2], [1]])
b = np.array([5])
c = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
a

array([[2],
       [1]])

In [28]:
b

array([5])

In [29]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
a.shape, b.shape, c.shape

((2, 1), (1,), (2, 2, 3))

In [31]:
# a (2,1) --> (1,2,1) 
# b (1,) --> (1,1,1)
# c (2,2,3) --> (2,2,3)


In [32]:
a+b+c

array([[[ 8,  9, 10],
        [10, 11, 12]],

       [[14, 15, 16],
        [16, 17, 18]]])

In [33]:
# 2+5+1 => 8
# 12+5+1 -> 18