In [1]:
# https://deepage.net/features/numpy-sort.html

* np.sort, np.argsort 

### np.sort

```
numpy.sort(a, axis=-1, kind='quicksort', order=None)
params:
- a : array_like
- axis : int or None
- kind : 'quicksort', 'mergesort', 'heapsort'
- order : 'string or string list'
returns :
- array
```


In [2]:
import numpy as np
a = np.random.randint(0, 100, size=20)
a

array([79, 84,  3, 10, 27, 41, 58, 23, 92, 50, 54, 81, 56, 35, 41, 80, 88,
       97, 32, 47])

In [3]:
np.sort(a)

array([ 3, 10, 23, 27, 32, 35, 41, 41, 47, 50, 54, 56, 58, 79, 80, 81, 84,
       88, 92, 97])

### np.argsort
```
numpy.argsort (a, axis = -1, kind = 'quicksort, order = None)
returns:
index array 
```


In [4]:
a = np.array([1, 3, 2])
a

array([1, 3, 2])

In [6]:
np.argsort(a) # index

array([0, 2, 1])

In [7]:
a[np.argsort(a)]

array([1, 2, 3])

## sort kind

In [10]:
import numpy as np
import time
def sort_comparison(n):
     result1 = np.empty(1000)
     for i in range(1000):
         a = np.random.rand(n)
         time1 = time.time()
         b = np.sort(a,kind='quicksort')
         time1 = time.time()- time1
         result1[i] = time1
     result2 = np.empty(1000)
     for i in range(1000):
         a = np.random.rand(n)
         time1 = time.time()
         b = np.sort(a, kind='mergesort')
         time1 = time.time()-time1
         result2[i] = time1
     result3 = np.empty(1000)
     for i in range(1000):
         a = np.random.rand(n)
         time1 = time.time()
         b = np.sort(a,kind='heapsort')
         time1 = time.time() - time1
         result3[i] = time1
     print ("quicksort average {}, max {}".format(np.average(result1), np.max(result1)))
     print ("mergesort average {}, max  {}".format(np.average(result2), np. max(result2)))
     print ("heapsort average {}, max {}".format(np.average(result3), np.max(result3)))  

In [11]:
sort_comparison(100)

quicksort average 6.981372833251953e-06, max 0.0011882781982421875
mergesort average 6.322860717773437e-06, max  0.0002288818359375
heapsort average 7.042646408081055e-06, max 3.409385681152344e-05


In [12]:
sort_comparison(1000)

quicksort average 4.442572593688965e-05, max 0.00029206275939941406
mergesort average 4.6743631362915036e-05, max  0.00010704994201660156
heapsort average 6.313705444335937e-05, max 0.0001480579376220703


In [13]:
sort_comparison(10000)

quicksort average 0.0005404922962188721, max 0.0010631084442138672
mergesort average 0.0006154365539550781, max  0.0011851787567138672
heapsort average 0.0007944533824920655, max 0.0015289783477783203


In [14]:
sort_comparison(100000)

quicksort average 0.006723747014999389, max 0.009920120239257812
mergesort average 0.008022084236145019, max  0.011155128479003906
heapsort average 0.01073415970802307, max 0.014153003692626953


## order

In [15]:
value = [('Alice', 25, 9.7), ('Bob', 12, 7.6), ('Catherine', 1, 8.6)]


In [16]:
dtype = [('name', 'S10'), ('ID', int), ('score', float)]

In [18]:
a = np.array(value, dtype=dtype)

In [19]:
a

array([(b'Alice', 25,  9.7), (b'Bob', 12,  7.6), (b'Catherine',  1,  8.6)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [20]:
np.sort(a, order='score')

array([(b'Bob', 12,  7.6), (b'Catherine',  1,  8.6), (b'Alice', 25,  9.7)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [21]:
np.sort(a, order='score')[::-1]

array([(b'Alice', 25,  9.7), (b'Catherine',  1,  8.6), (b'Bob', 12,  7.6)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [22]:
np.argsort(a, order='score')

array([1, 2, 0])

In [23]:
# multi order

In [24]:
np.sort(a, order=['score', 'ID'])

array([(b'Bob', 12,  7.6), (b'Catherine',  1,  8.6), (b'Alice', 25,  9.7)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [25]:
np.argsort(a, order=['score', 'ID'])

array([1, 2, 0])

# more examples

In [26]:
b = np.random.randint(0, 100, size=20).reshape(4,5)
b

array([[94,  9, 96,  1, 26],
       [13, 58, 75, 27, 61],
       [67, 65, 24, 70, 91],
       [90, 33, 41,  5, 29]])

In [27]:
np.sort(b)

array([[ 1,  9, 26, 94, 96],
       [13, 27, 58, 61, 75],
       [24, 65, 67, 70, 91],
       [ 5, 29, 33, 41, 90]])

In [28]:
np.argsort(b)

array([[3, 1, 4, 0, 2],
       [0, 3, 1, 4, 2],
       [2, 1, 0, 3, 4],
       [3, 4, 1, 2, 0]])

In [31]:
np.sort(b, axis=0)  # (95,13,67,90) -> (13,67,90,95)

array([[13,  9, 24,  1, 26],
       [67, 33, 41,  5, 29],
       [90, 58, 75, 27, 61],
       [94, 65, 96, 70, 91]])

In [32]:
np.argsort(b, axis=0)

array([[1, 0, 2, 0, 0],
       [2, 3, 3, 3, 3],
       [3, 1, 1, 1, 1],
       [0, 2, 0, 2, 2]])

In [34]:
np.sort(b, axis=1) # (94, 9, 96, 1, 26) -> (1, 9, 26, 94, 96)

array([[ 1,  9, 26, 94, 96],
       [13, 27, 58, 61, 75],
       [24, 65, 67, 70, 91],
       [ 5, 29, 33, 41, 90]])

In [35]:
np.argsort(b, axis=1)

array([[3, 1, 4, 0, 2],
       [0, 3, 1, 4, 2],
       [2, 1, 0, 3, 4],
       [3, 4, 1, 2, 0]])

In [36]:
#
c = np.random.randint(0, 100, size=(2,4,5))
c

array([[[36, 14, 84, 48, 89],
        [25, 89, 16, 30, 28],
        [87,  8, 62,  2, 74],
        [61, 27, 79, 10, 54]],

       [[38, 53, 36, 26, 41],
        [28, 63, 96, 14, 37],
        [78, 21, 40, 56, 18],
        [70, 55, 84, 28, 39]]])

In [37]:
np.sort(c)

array([[[14, 36, 48, 84, 89],
        [16, 25, 28, 30, 89],
        [ 2,  8, 62, 74, 87],
        [10, 27, 54, 61, 79]],

       [[26, 36, 38, 41, 53],
        [14, 28, 37, 63, 96],
        [18, 21, 40, 56, 78],
        [28, 39, 55, 70, 84]]])

In [41]:
np.sort(c, axis=0) #(36, 38), (14, 53) , (84, 36), (48, 26), (89, 41) --> 

array([[[36, 14, 36, 26, 41],
        [25, 63, 16, 14, 28],
        [78,  8, 40,  2, 18],
        [61, 27, 79, 10, 39]],

       [[38, 53, 84, 48, 89],
        [28, 89, 96, 30, 37],
        [87, 21, 62, 56, 74],
        [70, 55, 84, 28, 54]]])

In [43]:
np.sort(c, axis=1) #(36,25, 87, 61) -> (25, 36, 61, 87)

array([[[25,  8, 16,  2, 28],
        [36, 14, 62, 10, 54],
        [61, 27, 79, 30, 74],
        [87, 89, 84, 48, 89]],

       [[28, 21, 36, 14, 18],
        [38, 53, 40, 26, 37],
        [70, 55, 84, 28, 39],
        [78, 63, 96, 56, 41]]])

In [44]:
np.sort(c, axis=2)

array([[[14, 36, 48, 84, 89],
        [16, 25, 28, 30, 89],
        [ 2,  8, 62, 74, 87],
        [10, 27, 54, 61, 79]],

       [[26, 36, 38, 41, 53],
        [14, 28, 37, 63, 96],
        [18, 21, 40, 56, 78],
        [28, 39, 55, 70, 84]]])