In [1]:
# https://deepage.net/features/numpy-max.html

### np.amax / ndarray.max 사용법
* numpy.amax(a, axis=None, out=None, keepdims=np.NoValue)

In [2]:
import numpy as np
np.amax(np.array([1,2,3,2,1]))

3

In [3]:
arr = np.array([1,2,3,4]).reshape((2,2))
arr

array([[1, 2],
       [3, 4]])

In [4]:
np.amax(arr, axis=0)

array([3, 4])

In [5]:
np.amax(arr, axis=1)

array([2, 4])

In [6]:
np.amax(arr, keepdims=True)

array([[4]])

### ndarray.max
* numpy.ndarray.max(axis=None,out=None)

In [8]:
a = np.random.rand(20)
a

array([ 0.3520324 ,  0.52257073,  0.76608081,  0.92459714,  0.9311637 ,
        0.53296633,  0.40960307,  0.9508563 ,  0.14550298,  0.17805023,
        0.26925202,  0.05080002,  0.63713897,  0.41849899,  0.18072056,
        0.68174549,  0.87030469,  0.59205848,  0.19271306,  0.066512  ])

In [9]:
a.max()

0.95085630319373504

In [10]:
a = a.reshape((4,5))

In [11]:
a

array([[ 0.3520324 ,  0.52257073,  0.76608081,  0.92459714,  0.9311637 ],
       [ 0.53296633,  0.40960307,  0.9508563 ,  0.14550298,  0.17805023],
       [ 0.26925202,  0.05080002,  0.63713897,  0.41849899,  0.18072056],
       [ 0.68174549,  0.87030469,  0.59205848,  0.19271306,  0.066512  ]])

In [12]:
a.max()

0.95085630319373504

In [13]:
a.max(axis=0)

array([ 0.68174549,  0.87030469,  0.9508563 ,  0.92459714,  0.9311637 ])

In [14]:
a.max(axis=1)

array([ 0.9311637 ,  0.9508563 ,  0.63713897,  0.87030469])

In [15]:
b = np.random.rand(30).reshape((2,3,5))
b

array([[[ 0.77855828,  0.84656955,  0.83245072,  0.59084958,  0.78442842],
        [ 0.01087696,  0.53760812,  0.39306143,  0.02355814,  0.84644306],
        [ 0.20069129,  0.33995919,  0.35175687,  0.71946928,  0.70277619]],

       [[ 0.2277343 ,  0.59272568,  0.04495801,  0.47540025,  0.0264352 ],
        [ 0.98397924,  0.81100969,  0.32956222,  0.88718014,  0.39965304],
        [ 0.46766811,  0.95067515,  0.15575217,  0.17493825,  0.69458638]]])

In [16]:
b.max()

0.98397924147503457

In [17]:
b.max(axis=0)

array([[ 0.77855828,  0.84656955,  0.83245072,  0.59084958,  0.78442842],
       [ 0.98397924,  0.81100969,  0.39306143,  0.88718014,  0.84644306],
       [ 0.46766811,  0.95067515,  0.35175687,  0.71946928,  0.70277619]])

In [18]:
b.max(axis=1)

array([[ 0.77855828,  0.84656955,  0.83245072,  0.71946928,  0.84644306],
       [ 0.98397924,  0.95067515,  0.32956222,  0.88718014,  0.69458638]])

In [20]:
b.max(axis=2)

array([[ 0.84656955,  0.84644306,  0.71946928],
       [ 0.59272568,  0.98397924,  0.95067515]])

In [21]:
b = np.arange(10, dtype=np.float)
b[3] = np.NaN
b

array([  0.,   1.,   2.,  nan,   4.,   5.,   6.,   7.,   8.,   9.])

In [22]:
b.max() # naa 

nan

In [23]:
np.nanmax(b)

9.0