In [1]:
# https://deepage.net/features/numpy-argmax.html

### np.ndarray.argmax, np.argmax
```
np.ndarray.argmax (axis=None, out=None)
np.argmax(a, axis=None, out=None)
```


In [2]:
import numpy as np
a = np.random.randint(10, size=10)
a

array([3, 6, 3, 5, 7, 3, 4, 5, 4, 2])

In [4]:
np.argmax(a) # return index that indicate max-value

4

In [5]:
a.argmax()

4

In [6]:
b = np.random.randint(10, size=(3,4))
b

array([[1, 2, 8, 4],
       [7, 0, 2, 6],
       [5, 0, 5, 3]])

In [10]:
np.argmax(b) # index of 8

2

In [11]:
b.argmax()

2

In [12]:
#
b

array([[1, 2, 8, 4],
       [7, 0, 2, 6],
       [5, 0, 5, 3]])

In [13]:
np.argmax(b, axis=0)

array([1, 0, 0, 1])

In [14]:
np.argmax(b, axis=1)

array([2, 0, 0])

In [15]:
#
c = np.random.randint(10, size=(2,3,4))
c

array([[[9, 5, 4, 4],
        [5, 7, 5, 9],
        [6, 9, 9, 1]],

       [[1, 0, 4, 1],
        [2, 4, 9, 2],
        [3, 4, 5, 9]]])

In [17]:
np.argmax(c, axis=0) # (9,1), (5,0), (4,4), (4,1) --> 0, 0, 0, 0 / (5,2),(7,4),(5,9),(9,2) -> 0, 0, 1, 0

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
np.argmax(c, axis=1) # (9,5,6), (5,7,9), (4,5,9), (4,9,1) --> 0,2,2,1 

array([[0, 2, 2, 1],
       [2, 1, 1, 2]])

In [21]:
np.argmax(c, axis=2)# (9,5,4,4), (5,7,5,9),(6,9,9,1) --> (0,3,1)

array([[0, 3, 1],
       [2, 2, 3]])