In [1]:
# https://deepage.net/features/numpy-reshape.html

```
numpy.reshape(a, newshape, order='C')
params:
a : ndarray
newshape : int /int tuple 
order : C/F/A

returns:
ndarray
```


In [2]:
import numpy as np

In [3]:
a = np.arange(12) # 1차원 12개 요소
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = np.reshape(a, (3,4)) # 3x4
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.may_share_memory(a,b) # view

True

In [7]:
b[0,1] = 0

In [8]:
a

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# order (C/F/A)

In [11]:
c = np.arange(12)
d = np.reshape(c, (3,4), order='C') # row
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
d = np.reshape(c, (3,4), order="F") # colum
d

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [15]:
np.reshape(c, (3,5)) # error ValueError

ValueError: cannot reshape array of size 12 into shape (3,5)

In [16]:
a = np.arange(12)
np.reshape(a, (3,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.reshape(a, (-1, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
np.reshape(a, (-1, 5))

ValueError: cannot reshape array of size 12 into shape (5)

In [20]:
## ndarray.reshape : same

In [21]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b = np.arange(12).reshape((3,-1))

In [23]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
c = np.arange(15).reshape((3,4)) # error

ValueError: cannot reshape array of size 15 into shape (3,4)

## resize 
```
numpy.resize(a, newshape)
params:
a : ndarray
newshape : int / int tuple
returns:
ndarray
```
* order가 없음

In [25]:
a = np.arange(12)
np.reshape(a, (3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.resize(a, (3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [27]:
np.resize(a, (3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
# copy

In [29]:
b = np.resize(a, (3,4))
b[0,1] = 0

In [30]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
## ndarray.resize()