In [1]:
# https://deepage.net/features/numpy-append.html

In [2]:
# in python
a = [1,2,3]
a.append(2)
a

[1, 2, 3, 2]

In [3]:
a = [1,2,3]
a.extend([4,5,6])
a

[1, 2, 3, 4, 5, 6]

In [4]:
# np.append(arr, values, axis=None)

In [5]:
import numpy as np
a = np.arange(12)

In [6]:
np.append(a, [6,4,2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  4,  2])

In [7]:
b = np.arange(12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.append(b,[1,2,3,4]) # flatten & append

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [10]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.append(b, [[12,13,14,15]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.append(b, [12,13,14,15], axis=0) # 해당 차원에 맞는 입력 형태가 아니라서 오류가 발생

ValueError: all the input arrays must have same number of dimensions

In [14]:
c = np.arange(12).reshape((3,4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
d = np.linspace(0, 26, 12).reshape(3,4)

In [16]:
d

array([[  0.        ,   2.36363636,   4.72727273,   7.09090909],
       [  9.45454545,  11.81818182,  14.18181818,  16.54545455],
       [ 18.90909091,  21.27272727,  23.63636364,  26.        ]])

In [19]:
np.append(c, d, axis=0) # 6x4

array([[  0.        ,   1.        ,   2.        ,   3.        ],
       [  4.        ,   5.        ,   6.        ,   7.        ],
       [  8.        ,   9.        ,  10.        ,  11.        ],
       [  0.        ,   2.36363636,   4.72727273,   7.09090909],
       [  9.45454545,  11.81818182,  14.18181818,  16.54545455],
       [ 18.90909091,  21.27272727,  23.63636364,  26.        ]])

In [20]:
np.append(c, d, axis=1) # 3x8

array([[  0.        ,   1.        ,   2.        ,   3.        ,
          0.        ,   2.36363636,   4.72727273,   7.09090909],
       [  4.        ,   5.        ,   6.        ,   7.        ,
          9.45454545,  11.81818182,  14.18181818,  16.54545455],
       [  8.        ,   9.        ,  10.        ,  11.        ,
         18.90909091,  21.27272727,  23.63636364,  26.        ]])

In [21]:
## speed

In [22]:
def np_append():
    a = np.array([1,2,3])
    for i in range(10000):
        a = np.append(a, [i])
    return a
def list_append():
    a = [1,2,3]
    for i in range(10000):
        a.append(i)
    return np.array(a)

In [23]:
%timeit np_append()

75.3 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
%timeit list_append()

1.59 ms ± 11.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
