In [1]:
# https://deepage.net/features/numpy-transpose.html

$a=(a_1, a_2, ..., a_n), a^t = \begin{pmatrix} a_1  \\ a_2 \\ ... \\ a_n \end{pmatrix}$

$b = \begin{pmatrix} b_1  \\ b_2 \\ ... \\ b_n \end{pmatrix}, b^t=(b_1, b_2, ..., b_n), $

$A=\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}$

$A^t=\begin{pmatrix} a_{11} & a_{21} \\ a_{12} & a_{22} \end{pmatrix}$

$B=\begin{pmatrix} b_{11} & b_{12}& b_{13}\\ b_{21} & b_{22}& b_{23} \end{pmatrix}$

$B=\begin{pmatrix} b_{11} & b_{21} \\ b_{12} & b_{22} \\ b_{13} & b_{23}\end{pmatrix}$

$a(i,j) -> a^`(j,i)$

In [2]:
## transpose

In [3]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [5]:
a.transpose(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [6]:
a.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [7]:
a.transpose(0,1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
#
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [9]:
b.transpose()

array([0, 1, 2, 3, 4, 5])

In [10]:
b = b.reshape((1,6))
b

array([[0, 1, 2, 3, 4, 5]])

In [11]:
b.transpose()

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
# 3d
c = np.arange(24).reshape(4,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [13]:
c.transpose()

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [14]:
c.transpose(1, 0, 2)

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]])

In [15]:
c.shape

(4, 3, 2)

In [16]:
np.transpose(c)

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [18]:
np.transpose(c).shape

(2, 3, 4)

In [19]:
np.transpose(c, (1,0,2))

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]])

In [20]:
np.transpose(c, (1,0,2)).shape

(3, 4, 2)

### numpy.ndarray.T

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [23]:
b

array([[0, 1, 2, 3, 4, 5]])

In [24]:
b.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [26]:
c.T

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [28]:
a.transpose().shape == a.T.shape

True

In [29]:
b.transpose().shape == b.T.shape

True

In [30]:
c.transpose().shape == c.T.shape

True