In [2]:
#https://deepage.net/features/numpy-allany.html

In [1]:
# numpy.all
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html

In [12]:
import numpy as np
a = np.array( [
    [1,1,1],
    [1,0,1],
    [1,0,1],
])

In [13]:
np.all(a)

False

In [14]:
b = np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
np.all(b)

True

In [16]:
np.all(a<2)

True

In [17]:
np.all(b%3<2)

True

In [18]:
# axis
np.all(a, axis=0)

array([ True, False,  True], dtype=bool)

In [19]:
np.all(a, axis=1)

array([ True, False, False], dtype=bool)

In [20]:
np.all(a, axis=0, keepdims=True)

array([[ True, False,  True]], dtype=bool)

In [21]:
a.all()

False

In [22]:
b.all()

True

In [23]:
a.all(axis=1)

array([ True, False, False], dtype=bool)

In [24]:
(a<2).all()

True

In [25]:
a.all(keepdims=True)

array([[False]], dtype=bool)

In [27]:
## np.any : [true, false, false] --> any --> True

In [31]:
a = np.random.randint(10, size=(2,3))
a

array([[5, 8, 5],
       [4, 9, 1]])

In [32]:
np.any(a==9)

True

In [33]:
np.any(a==2)

False

In [34]:
np.any(a%2==0, axis=0) # y

array([ True,  True, False], dtype=bool)

In [36]:
np.any(a%2==0, axis=1) # x

array([ True,  True], dtype=bool)

In [37]:
np.any(a%2==1, axis=1, keepdims=True)

array([[ True],
       [ True]], dtype=bool)

In [38]:
np.any(a%2==1, axis=0, keepdims=True)

array([[ True,  True,  True]], dtype=bool)