In [1]:
# https://deepage.net/features/numpy-stack.html

* ndarray는 + 연산자로 결합할수 없음
* `vstack`, `hstack`

## np.hstack
```
numpy.hstack(tup)
```

In [1]:
import numpy as np
a = np.arange(12)
b = np.arange(2)

In [2]:
a, b

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([0, 1]))

In [3]:
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

In [4]:
c = np.arange(2).reshape(1,2)
c

array([[0, 1]])

In [5]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions

In [6]:
d = np.arange(5).reshape(1, 5)
d

array([[0, 1, 2, 3, 4]])

In [7]:
np.hstack((d,c))

array([[0, 1, 2, 3, 4, 0, 1]])

In [8]:
# 3차원의 경우에는 axis=1방향으로 연결함

In [10]:
e = np.arange(12).reshape(2, 2, 3)
f = np.arange(6).reshape(2,1,3)

In [11]:
e

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [12]:
f

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [13]:
np.hstack((e,f))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

## np.vstack
```
np.vstack(tup)
```


In [14]:
a = np.arange(12)
b = np.arange(2)

In [15]:
a, b

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([0, 1]))

In [17]:
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

In [18]:
c = np.arange(2).reshape(1, 2)
c

array([[0, 1]])

In [19]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [21]:
np.vstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [22]:
d = np.arange(4).reshape(2, 2)
d

array([[0, 1],
       [2, 3]])

In [23]:
c

array([[0, 1]])

In [24]:
np.vstack((c,d))

array([[0, 1],
       [0, 1],
       [2, 3]])

In [25]:
np.vstack((d, c))

array([[0, 1],
       [2, 3],
       [0, 1]])

In [26]:
# 3d

In [27]:
e = np.arange(24).reshape(4,3,2)
f = np.arange(6).reshape(1,3,2)

In [28]:
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [29]:
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [32]:
g = np.vstack((e,f))

In [33]:
g

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

In [34]:
g.shape

(5, 3, 2)