In [1]:
#https://deepage.net/features/numpy-where.html

* `np.where` : 조건식을 지정하여, 원하는 요소의 인덱스를 얻을 수 있음

### np.where
```
numpy.where (condtion [x,y])

returns : 
-- index
```

### 조건 지정

In [2]:
import numpy as np
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [5]:
np.where(a<10)  # return index

(array([6, 7, 8, 9]),)

In [6]:
a[np.where(a<10)] # return array using index

array([8, 6, 4, 2])

In [7]:
a = np.arange(12).reshape((3,4))

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.where(a % 2 == 0)

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))

In [10]:
a[np.where(a%2==0)]

array([ 0,  2,  4,  6,  8, 10])

### np.where 삼항 연산

In [12]:
np.where(a%2==0, 'even', 'odd') # np.where(condtion, true, false)

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']],
      dtype='<U4')

In [13]:
np.where(a%2==0, 'even')

ValueError: either both or neither of x and y should be given

In [14]:
b = np.reshape(a, (3,4))

In [15]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
c = b**2

In [17]:
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [18]:
np.where(b%2==0, b, c)

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

In [19]:
np.where(b%2==0, b, (10, 8, 6, 4))

array([[ 0,  8,  2,  4],
       [ 4,  8,  6,  4],
       [ 8,  8, 10,  4]])

In [20]:
d = b+1

In [21]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
np.where(d%2==0, d, (10, 8, 6, 4))

array([[10,  2,  6,  4],
       [10,  6,  6,  8],
       [10, 10,  6, 12]])