## 1차원 배열로 변환
* `flatten`

### ndarray.flatten

```
numpy.ndarray.flatten(order='C')
```


In [1]:
import numpy as np
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [2]:
b = a.flatten()

In [3]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.shape

(2, 5)

In [5]:
b.shape

(10,)

In [6]:
# 3d matrix

In [7]:
c = np.arange(12).reshape(2,2,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
d = c.flatten()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
c.shape

(2, 2, 3)

In [10]:
d.shape

(12,)

## 성능
* vs `np.ravel`
* np.ravel 은 사본을 생성하지 않음
* `np.ravel`이 `np.flatten`보다 빠르게 작성함

In [11]:
import numpy as np
arr = np.repeat(5, 10000).reshape(250,40)

In [12]:
%timeit arr.flatten()

4.04 µs ± 60.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit np.ravel(arr)

1.37 µs ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
