In [1]:
# https://deepage.net/features/numpy-ones.html

In [2]:
import numpy as np

In [3]:
np.ones(3)

array([ 1.,  1.,  1.])

In [4]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
np.ones(4, dtype="float32")

array([ 1.,  1.,  1.,  1.], dtype=float32)

In [6]:
np.ones(4, dtype="int8")

array([1, 1, 1, 1], dtype=int8)

In [7]:
np.ones((2,3), dtype="complex")

array([[ 1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j]])

In [8]:
# ones_like

In [9]:
a = np.ones((2,3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
b = np.ones(a.shape)

In [11]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
c = np.ones_like(a)
c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
a = np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
b = np.array([2,3,4], dtype="int8")
b

array([2, 3, 4], dtype=int8)

In [16]:
np.ones_like(b)

array([1, 1, 1], dtype=int8)