In [1]:
# https://deepage.net/features/numpy-zeros.html

In [2]:
# np.zeros / np.empty / np.zeros_like

### np.zeros
```
numpy.zeros(shape, dtype=float, order='C')
```

In [3]:
import numpy as np

In [4]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

### np.empty, np.zeros_liike 

In [7]:
# np.empty : 0으로 초기화 할 필요가 없는 초기화
def zeros():
    for i in range(10000):
        _ = np.zeros((1,i))

def empty():
    for i in range(10000):
        _ = np.empty((1,i))

In [8]:
%timeit zeros()

18.9 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%timeit empty()

5.47 ms ± 126 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
# empty is 2-times faster than zeros()

### np.zeros_like
```
numpy.zeros_like(a, dtype=None, order='K', subok=True)
a : array_like -> 생성하는 배열의 shape가 필요
```

In [12]:
a = np.arange(12).reshape(1,4,3)
b = np.zeros(a.shape)

In [13]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
b

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [15]:
b = np.zeros_like(a)

In [16]:
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])