In [1]:
# https://deepage.net/features/numpy-empty.html

`numpy.empty` : 초기화하지 않고 배열을 생성하는 함수

### np.empty
```
np.emtpy(shape, dtype=float, order='C')
returns : ndarray
```


In [4]:
import numpy as np
np.empty(10) # 초기화 하지 않은 비어있는 행렬 반환

array([  0.00000000e+000,   0.00000000e+000,   2.96439388e-323,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   1.48219694e-323,
         0.00000000e+000])

In [8]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
np.empty((5,5))

array([[  0.00000000e+000,  -2.00389564e+000,   6.42285340e-323,
         -2.00389564e+000,   2.18694824e-314],
       [  2.18697243e-314,   2.18697240e-314,   2.18697237e-314,
          2.18697205e-314,   2.18697202e-314],
       [  2.18697474e-314,   2.18697145e-314,   2.18697471e-314,
          2.18697155e-314,   2.18697151e-314],
       [  2.18697148e-314,   2.18697170e-314,   2.18697468e-314,
          0.00000000e+000,  -2.68678478e+154],
       [  1.09385187e-303,   2.36998464e-303,   2.22389624e-042,
          2.18007982e-314,   0.00000000e+000]])

In [11]:
np.empty(5,dtype=np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [12]:
np.empty(10, dtype=np.bool)

array([False, False,  True, False, False, False, False, False,  True, False], dtype=bool)

In [13]:
np.empty(10, dtype=complex)

array([  0.00000000e+000 +0.00000000e+000j,
         7.90505033e-323 +0.00000000e+000j,
         5.58766970e+252 +4.82337433e+228j,
         5.50348562e-144 +1.16097020e-028j,
         3.93232303e-062 +2.73458740e-052j,
         2.17529585e-076 +3.97062373e+246j,
         1.16318408e-028 +1.79617324e-052j,
         4.42246130e-062 +5.40246243e-038j,
         4.56075234e-037 +5.04621361e+180j,
         8.37170571e-144 +1.89020758e+219j])

## 다른 생성 함수와의 비교

* np.zeros, np.ones 속도 비교
* np.empty의 속도가 다른 생성함수들 보다 3~6배 속도차이를 보임

In [14]:
%timeit np.zeros(10000)

3.75 µs ± 28 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%timeit np.ones(10000)

6.42 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit np.empty(10000)

1.07 µs ± 12.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
