In [1]:
# https://deepage.net/features/numpy-linspace.html

## 산술급수
* 항 사이의 값 차이가 일정한 수열의 수
```
5,7,9,11,13,15,...
```

## np.linspace

```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```


In [3]:
import numpy as np

In [5]:
np.linspace(0, 1) # 50 numbers.

array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

In [6]:
np.linspace(0, 49)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.])

In [7]:
np.linspace(0, 2, 3)

array([ 0.,  1.,  2.])

In [8]:
np.linspace(0, -2, 3)

array([ 0., -1., -2.])

In [9]:
np.linspace(0, 2, num=3)

array([ 0.,  1.,  2.])

In [10]:
# endpoint

In [11]:
np.linspace(0, 2, num=3, endpoint=False)

array([ 0.        ,  0.66666667,  1.33333333])

In [12]:
np.linspace(0, 2, num=3, endpoint=True)

array([ 0.,  1.,  2.])

In [13]:
# retstep

In [15]:
np.linspace(0, 2, retstep=True) # return step value

(array([ 0.        ,  0.04081633,  0.08163265,  0.12244898,  0.16326531,
         0.20408163,  0.24489796,  0.28571429,  0.32653061,  0.36734694,
         0.40816327,  0.44897959,  0.48979592,  0.53061224,  0.57142857,
         0.6122449 ,  0.65306122,  0.69387755,  0.73469388,  0.7755102 ,
         0.81632653,  0.85714286,  0.89795918,  0.93877551,  0.97959184,
         1.02040816,  1.06122449,  1.10204082,  1.14285714,  1.18367347,
         1.2244898 ,  1.26530612,  1.30612245,  1.34693878,  1.3877551 ,
         1.42857143,  1.46938776,  1.51020408,  1.55102041,  1.59183673,
         1.63265306,  1.67346939,  1.71428571,  1.75510204,  1.79591837,
         1.83673469,  1.87755102,  1.91836735,  1.95918367,  2.        ]),
 0.040816326530612242)

In [16]:
np.linspace(0, 2, num=3, retstep=True)

(array([ 0.,  1.,  2.]), 1.0)

In [18]:
np.linspace(0, 2, num=3, retstep=False)

array([ 0.,  1.,  2.])

In [19]:
# dtype

In [20]:
np.linspace(0, 2, num=3)

array([ 0.,  1.,  2.])

In [21]:
a = np.linspace(0, 1, 3)
a

array([ 0. ,  0.5,  1. ])

In [22]:
a.dtype

dtype('float64')

In [23]:
np.linspace(0, 2, num=3, dtype='int')

array([0, 1, 2])

In [24]:
np.linspace(0, 1, num=4, dtype='float32')

array([ 0.        ,  0.33333334,  0.66666669,  1.        ], dtype=float32)

In [25]:
np.linspace(0, 1, num=4, dtype='float64')

array([ 0.        ,  0.33333333,  0.66666667,  1.        ])