In [1]:
# https://deepage.net/features/numpy-cr.html

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [5]:
np.r_[2,5,3, np.array([2,3,]), 4.2]

array([2. , 5. , 3. , 2. , 3. , 4.2])

In [6]:
c = np.zeros((2,3))

In [7]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.r_[c,d]

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
d = np.ones((3,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.r_[c,d]

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [15]:
## slice

In [16]:
np.r_[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.r_[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.r_[-10:]

array([], dtype=int64)

In [19]:
np.r_[0:10:2]

array([0, 2, 4, 6, 8])

In [20]:
np.r_[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [22]:
np.r_[0:10:10j]

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.r_[0:9:20j]

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [25]:
np.r_[0:10, 0,4, np.array([3,3])]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4, 3, 3])

### 축 지정
* `a,b,c` : default `0,0,-1`
* a : 축방향으로 배열 결합
* b : 완성 배열의 차원수 지정(최소)
* c

In [27]:
a = np.ones( (2,2))
a

array([[1., 1.],
       [1., 1.]])

In [28]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [31]:
np.r_['1', a,b] # axis=1 concatenation

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [32]:
np.r_['1', a, b].shape

(2, 4)

In [34]:
np.r_['0', a, b] # axis=0

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.r_['0', a, b].shape

(4, 2)

In [36]:
np.r_[a,b]

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [37]:
c = np.ones((2,2,2))
d = np.zeros((2,2,2))

In [38]:
c

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [39]:
d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [41]:
np.r_['0', c, d], np.r_['0', c, d].shape

(array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]],
 
        [[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]), (4, 2, 2))

In [42]:
np.r_['1', c, d], np.r_['1', c, d].shape

(array([[[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]],
 
        [[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]]]), (2, 4, 2))

In [43]:
np.r_['2', c, d], np.r_['2', c, d].shape

(array([[[1., 1., 0., 0.],
         [1., 1., 0., 0.]],
 
        [[1., 1., 0., 0.],
         [1., 1., 0., 0.]]]), (2, 2, 4))

In [44]:
## b

In [45]:
np.r_['0,2', [0,1,2], [3,3,3]]

array([[0, 1, 2],
       [3, 3, 3]])

In [46]:
np.r_['0,2', [0,1,2], [3,3,3]].shape

(2, 3)

In [47]:
np.r_['0,3', [0,1,2], [3,3,3]]

array([[[0, 1, 2]],

       [[3, 3, 3]]])

In [48]:
np.r_['0,3', [0,1,2], [3,3,3]].shape

(2, 1, 3)

In [49]:
np.r_['-1,4', [0,1,2], [3,3,3]]

array([[[[0, 1, 2, 3, 3, 3]]]])

In [50]:
np.r_['-1,4', [0,1,2], [3,3,3]].shape

(1, 1, 1, 6)

In [51]:
np.r_['0,2,-1', [0,1,2], [3,3,3]]

array([[0, 1, 2],
       [3, 3, 3]])

In [52]:
np.r_['0,2,-1', [0,1,2], [3,3,3]].shape

(2, 3)

In [53]:
np.r_['0,2,0', [0,1,2], [3,3,3]]

array([[0],
       [1],
       [2],
       [3],
       [3],
       [3]])

In [54]:
np.r_['0,2,0', [0,1,2], [3,3,3]].shape

(6, 1)

In [55]:
np.r_['0,3,0', [0,1,2], [3,3,3]]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[3]],

       [[3]]])

In [56]:
np.r_['0,3,0', [0,1,2], [3,3,3]].shape

(6, 1, 1)

## numpy.c_

In [57]:
a = np.ones((3,2))
b = np.zeros((3,3))

In [58]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.c_[a,b]

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [63]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [64]:
np.c_[a,c]

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [65]:
np.c_[a,c].shape

(3, 3)

In [66]:
np.c_[[1,2,3],[4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
# vertical concatenation

In [68]:
np.c_[ [[1,2,3]], [[4,5,6]], 2, 3]

array([[1, 2, 3, 4, 5, 6, 2, 3]])