In [1]:
# https://deepage.net/features/numpy-nonzero.html

## np.nonzero
- 요소가 0이 아닌 인덱스를 얻어오는 함수

In [2]:
import numpy as np

In [3]:
a = np.random.randint(0, 10, size=20)
a

array([9, 3, 4, 4, 1, 2, 2, 5, 1, 0, 5, 8, 7, 2, 1, 4, 0, 7, 3, 2])

In [7]:
np.nonzero(a) # exclude 9th index (0)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 17, 18,
        19]),)

In [8]:
a.nonzero()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 17, 18,
        19]),)

In [9]:
a[np.nonzero(a)]

array([9, 3, 4, 4, 1, 2, 2, 5, 1, 5, 8, 7, 2, 1, 4, 7, 3, 2])

In [10]:
b = np.random.randint(0, 10, size=(4,5))
b

array([[8, 7, 2, 5, 0],
       [5, 7, 6, 8, 0],
       [2, 5, 0, 0, 8],
       [2, 6, 4, 6, 8]])

In [11]:
np.nonzero(b)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 4, 0, 1, 2, 3, 4]))

In [12]:
b.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 4, 0, 1, 2, 3, 4]))

In [13]:
b[b.nonzero()]

array([8, 7, 2, 5, 5, 7, 6, 8, 2, 5, 8, 2, 6, 4, 6, 8])

## np.where, np.argwhere 비교
* `np.where(x!=0)` 방법으로 같은 효과를 얻을 수 있음

In [14]:
a = np.random.randint(0, 10, size=(100, 100))
b = np.ones(shape=(100, 100))


In [15]:
np.where(a != 0, a, b)

array([[9., 9., 1., ..., 6., 3., 8.],
       [6., 8., 4., ..., 2., 6., 5.],
       [1., 8., 7., ..., 6., 6., 1.],
       ...,
       [6., 1., 1., ..., 5., 6., 9.],
       [4., 9., 1., ..., 1., 1., 7.],
       [9., 7., 6., ..., 4., 6., 6.]])

In [16]:
import numpy as np
a = np.random.randint(0, 10, size=(100, 100))

In [17]:
np.nonzero(a)

(array([ 0,  0,  0, ..., 99, 99, 99]), array([ 0,  1,  2, ..., 97, 98, 99]))

In [18]:
np.where(a != 0)

(array([ 0,  0,  0, ..., 99, 99, 99]), array([ 0,  1,  2, ..., 97, 98, 99]))

* `np.argwhere`는 반환된 인덱스의 전치행렬을 반환한다.
* `np.argwhere(a) == np.transpose(np.nonzero(a))`

In [19]:
np.argwhere( a!=0)

array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       ...,
       [99, 97],
       [99, 98],
       [99, 99]])

In [20]:
np.transpose(np.nonzero(a))

array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       ...,
       [99, 97],
       [99, 98],
       [99, 99]])