## numpy.tile

```
numpy.tile ( A, reps)
```


In [1]:
import numpy as np
a = np.array([0,1,2])

In [2]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [3]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [4]:
np.tile(a, (2,3,4))

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]])

In [5]:
b = np.arange(6).reshape(2, 3)

In [6]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
np.tile(b, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [8]:
np.tile(b, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [9]:
np.tile(b, (2,1,2))

array([[[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]],

       [[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]]])

## np.tile 함수 및 broadcast

In [10]:
a = np.arange(10000).reshape(-1, 1)
b = np.arange(10000).reshape(1, -1)

In [14]:
a, a.shape

(array([[   0],
        [   1],
        [   2],
        ...,
        [9997],
        [9998],
        [9999]]), (10000, 1))

In [15]:
b, b.shape

(array([[   0,    1,    2, ..., 9997, 9998, 9999]]), (1, 10000))

In [16]:
a*b, (a*b).shape

(array([[       0,        0,        0, ...,        0,        0,        0],
        [       0,        1,        2, ...,     9997,     9998,     9999],
        [       0,        2,        4, ...,    19994,    19996,    19998],
        ...,
        [       0,     9997,    19994, ..., 99940009, 99950006, 99960003],
        [       0,     9998,    19996, ..., 99950006, 99960004, 99970002],
        [       0,     9999,    19998, ..., 99960003, 99970002, 99980001]]),
 (10000, 10000))

### tile

In [17]:
np.tile(a, (1,10000)) * np.tile(b, (10000,1))

array([[       0,        0,        0, ...,        0,        0,        0],
       [       0,        1,        2, ...,     9997,     9998,     9999],
       [       0,        2,        4, ...,    19994,    19996,    19998],
       ...,
       [       0,     9997,    19994, ..., 99940009, 99950006, 99960003],
       [       0,     9998,    19996, ..., 99950006, 99960004, 99970002],
       [       0,     9999,    19998, ..., 99960003, 99970002, 99980001]])

### speed

In [18]:
a = np.arange(10000).reshape(-1, 1)
b = np.arange(10000)

In [19]:
%timeit a*b

523 ms ± 6.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
%timeit np.tile(a, (1,10000))*np.tile(b, (10000,1))

2.02 s ± 29.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


* np.tile보다는 broadcast의 속도가 많이 빠르다 (4배?)

### tile은 언제?
* broadcast를 적용하지 못할 경우
* 주기적으로 있는 배열 값에 대해서 적용하고 싶을때

In [25]:
c = np.random.rand(10)
b = np.array([0, 1, 0, 2, 1])
b = np.tile(b, 2)

In [26]:
c

array([0.72881455, 0.95631551, 0.17644499, 0.20529091, 0.1003325 ,
       0.23234377, 0.61458669, 0.14363001, 0.19156475, 0.17947722])

In [27]:
b

array([0, 1, 0, 2, 1, 0, 1, 0, 2, 1])

In [28]:
c * b

array([0.        , 0.95631551, 0.        , 0.41058181, 0.1003325 ,
       0.        , 0.61458669, 0.        , 0.3831295 , 0.17947722])