In [1]:
# https://deepage.net/features/numpy-diff.html

요소간의 미분을 취함

$ \frac{\partial u}{\partial x} \to \frac{u(x+\Delta x) - u(x)}{\Delta x} \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\ \\ \frac{\partial^2 u}{\partial x^2} \to \frac{u(x+\Delta x) - 2u(x) + u(x-\Delta x)}{(\Delta x)^2} \ \ \ \ \ \ \ \\ \\  \frac{\partial^3 u}{\partial x^3} \to \frac{u(x+2\Delta x) - 3u(x+\Delta x) + 3u(x) - u(x-\Delta x)}{(\Delta x) ^3} \\  $

* n = 1
```
y[i] = x[i+1]-x[i]
```
* n =2
```
y[i] = x[i+2] - 2x[i+1] + x[i]
```


In [2]:
import numpy as np
a = np.array([1, 2, 4, 1, 6, 8, 3])

In [3]:
np.diff(a, n=1) # n=1~

array([ 1,  2, -3,  5,  2, -5])

In [4]:
np.diff(a, n=2)

array([ 1, -5,  8, -3, -7])

In [5]:
np.diff(a, n=3)

array([ -6,  13, -11,  -4])

In [6]:
np.diff(a, n=4)

array([ 19, -24,   7])

In [7]:
b = np.random.randint(10, size=(5,5))
b

array([[0, 0, 2, 3, 5],
       [9, 7, 0, 5, 5],
       [5, 3, 3, 4, 2],
       [8, 5, 5, 1, 6],
       [7, 8, 3, 9, 8]])

In [8]:
np.diff(b, axis=-1)

array([[ 0,  2,  1,  2],
       [-2, -7,  5,  0],
       [-2,  0,  1, -2],
       [-3,  0, -4,  5],
       [ 1, -5,  6, -1]])

In [9]:
np.diff(b, axis=0)

array([[ 9,  7, -2,  2,  0],
       [-4, -4,  3, -1, -3],
       [ 3,  2,  2, -3,  4],
       [-1,  3, -2,  8,  2]])

In [10]:
np.diff(b, axis=1, n=2)

array([[ 2, -1,  1],
       [-5, 12, -5],
       [ 2,  1, -3],
       [ 3, -4,  9],
       [-6, 11, -7]])

## cumulative sum 
* np.cumsum
* 누적합
```
[1, 2, 3]
-->
[1, (1+2), (1+2+3]
-> 
[1, 3, 6]
```

In [12]:
import numpy as np


In [13]:
a = np.random.randint(10, size=20)
a

array([1, 3, 8, 5, 0, 2, 6, 8, 9, 0, 8, 6, 7, 6, 1, 3, 4, 9, 8, 5])

In [14]:
np.cumsum(a)

array([ 1,  4, 12, 17, 17, 19, 25, 33, 42, 42, 50, 56, 63, 69, 70, 73, 77,
       86, 94, 99])

In [15]:
a.cumsum()

array([ 1,  4, 12, 17, 17, 19, 25, 33, 42, 42, 50, 56, 63, 69, 70, 73, 77,
       86, 94, 99])

In [16]:
np.cumsum(a, dtype='float32')

array([ 1.,  4., 12., 17., 17., 19., 25., 33., 42., 42., 50., 56., 63.,
       69., 70., 73., 77., 86., 94., 99.], dtype=float32)

In [17]:
a.cumsum(dtype='float32')

array([ 1.,  4., 12., 17., 17., 19., 25., 33., 42., 42., 50., 56., 63.,
       69., 70., 73., 77., 86., 94., 99.], dtype=float32)

In [18]:
b = np.random.rand(3,4)*10
b

array([[3.16792816, 8.25638691, 9.06673438, 6.33527829],
       [0.83717783, 3.0771242 , 3.27067445, 4.94150032],
       [2.86137112, 2.3771857 , 8.85439393, 5.5782004 ]])

In [19]:
c = np.random.randint(10, size=10, dtype='int8')
c

array([1, 9, 6, 7, 4, 7, 5, 4, 1, 9], dtype=int8)

In [20]:
c.cumsum()

array([ 1, 10, 16, 23, 27, 34, 39, 43, 44, 53])

In [21]:
c.cumsum().dtype

dtype('int64')

In [22]:
d = c.cumsum(dtype='int8')
d

array([ 1, 10, 16, 23, 27, 34, 39, 43, 44, 53], dtype=int8)

In [23]:
d.dtype

dtype('int8')

In [24]:
b

array([[3.16792816, 8.25638691, 9.06673438, 6.33527829],
       [0.83717783, 3.0771242 , 3.27067445, 4.94150032],
       [2.86137112, 2.3771857 , 8.85439393, 5.5782004 ]])

In [27]:
np.cumsum(b) # (3.16 / 3.16+8.25 / ....)

array([ 3.16792816, 11.42431507, 20.49104945, 26.82632775, 27.66350558,
       30.74062978, 34.01130423, 38.95280455, 41.81417567, 44.19136137,
       53.0457553 , 58.6239557 ])

In [28]:
np.cumsum(b, axis=1)

array([[ 3.16792816, 11.42431507, 20.49104945, 26.82632775],
       [ 0.83717783,  3.91430204,  7.18497648, 12.1264768 ],
       [ 2.86137112,  5.23855682, 14.09295075, 19.67115115]])

In [29]:
np.cumsum(b, axis=0) # 3.16+0.83

array([[ 3.16792816,  8.25638691,  9.06673438,  6.33527829],
       [ 4.005106  , 11.33351111, 12.33740883, 11.27677861],
       [ 6.86647712, 13.71069681, 21.19180276, 16.85497901]])

In [31]:
b.cumsum(axis=0)

array([[ 3.16792816,  8.25638691,  9.06673438,  6.33527829],
       [ 4.005106  , 11.33351111, 12.33740883, 11.27677861],
       [ 6.86647712, 13.71069681, 21.19180276, 16.85497901]])