In [1]:
# https://deepage.net/features/numpy-ravel.html

## np.ravel

* `np.flatten`보다는 빠르게 flatten기능을 사용 할수 있음

```
numpy.ravel(a, order='C')
```

### order
* `order`을 이용하여 데이터의 읽는 순서를 지정 할 수 있음
* 'C'는 열 방향 (최소 차원 축 방향)
* 'F'는 반대 방향 (최고 차원 축 방향)
* 'A' : 원래의 배열 `order='F'` (fortran 스타일)
* 'K' : 메모리에 있는 순서



In [2]:
import numpy as np
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.ravel(order='C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.ravel(order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [7]:
a.ravel(order='A')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.ravel(order='K')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = np.arange(10).reshape(2, 5, order='F')
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [10]:
b.ravel(order='F')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b.ravel(order='C')

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [12]:
b.ravel(order='A')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b.ravel()

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [14]:
c = b.T

In [15]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
c.ravel(order='K')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
c.T.ravel(order='K')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### flatten과의 차이
* `ravel`은 원본이 변경됨

In [18]:
import numpy
a = np.random.randint(10, size=(1000, 1000))

In [19]:
%timeit a.flatten()

641 µs ± 9.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%timeit a.ravel()

307 ns ± 6.65 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
b = a.flatten()
c = a.ravel()

In [22]:
a[0, 20] = 23

In [23]:
b[20]

3

In [24]:
c[20]

23