In [1]:
# https://deepage.net/features/numpy-std.html

## 표준편차

```python
numpy.std (a, axis = None, dtype = None, out = None, ddof = 0, keepdims = False)
```

In [2]:
import numpy as np

In [3]:
a = np.random.rand(10)
a

array([0.52461118, 0.44630367, 0.67881523, 0.72847747, 0.37761561,
       0.31753814, 0.7390976 , 0.07810871, 0.06866558, 0.73101688])

In [4]:
np.std(a)

0.24513663820310283

In [5]:
## axis

In [6]:
b = np.random.rand(2,3,4)
b

array([[[0.97859999, 0.72538528, 0.65171307, 0.95534426],
        [0.30191872, 0.59760155, 0.19958895, 0.78527434],
        [0.1753958 , 0.29929973, 0.16355564, 0.18650518]],

       [[0.11729925, 0.51762534, 0.21573267, 0.72676811],
        [0.16516706, 0.37343812, 0.25899564, 0.15829185],
        [0.4746563 , 0.95348079, 0.25475295, 0.20941091]]])

In [7]:
np.std(b, axis=0)

array([[0.43065037, 0.10387997, 0.2179902 , 0.11428807],
       [0.06837583, 0.11208171, 0.02970334, 0.31349125],
       [0.14963025, 0.32709053, 0.04559865, 0.01145287]])

In [8]:
np.std(b, axis=1)

array([[0.35261603, 0.17853153, 0.22211416, 0.32974094],
       [0.15838735, 0.24657868, 0.01947154, 0.25678285]])

In [9]:
np.std(b, axis=2)

array([[0.14186574, 0.23294244, 0.05436655],
       [0.24205365, 0.08723322, 0.29494724]])

In [10]:
np.std(b, axis=(0,1))

array([0.29711358, 0.21842494, 0.16467888, 0.32648414])

In [12]:
np.std(b, axis=(0,1,2))

0.2828378035608932

In [13]:
np.std(b)

0.2828378035608932

In [14]:
np.std(b, dtype='float16')

0.283

In [15]:
np.std(b, dtype='complex')

(0.2828378035608933+0j)

In [25]:
c = np.empty( (2,3))

In [26]:
np.std(b, axis=2 , out=c)

array([[0.14186574, 0.23294244, 0.05436655],
       [0.24205365, 0.08723322, 0.29494724]])

In [27]:
c

array([[0.14186574, 0.23294244, 0.05436655],
       [0.24205365, 0.08723322, 0.29494724]])

In [28]:
np.std(b)

0.2828378035608932

In [30]:
np.std(b, ddof=1) ## ddof

0.2889210329120045

In [31]:
## keepdims

In [32]:
np.std(b, keepdims=True)

array([[[0.2828378]]])

In [33]:
np.std(b, axis=0, keepdims=True)

array([[[0.43065037, 0.10387997, 0.2179902 , 0.11428807],
        [0.06837583, 0.11208171, 0.02970334, 0.31349125],
        [0.14963025, 0.32709053, 0.04559865, 0.01145287]]])

In [34]:
b/ np.std(b, axis=0, keepdims=True)

array([[[ 2.27237699,  6.98291756,  2.98964391,  8.35908982],
        [ 4.41557661,  5.33183809,  6.71940992,  2.50493227],
        [ 1.17219478,  0.91503639,  3.58685232, 16.28458445]],

       [[ 0.27237699,  4.98291756,  0.98964391,  6.35908982],
        [ 2.41557661,  3.33183809,  8.71940992,  0.50493227],
        [ 3.17219478,  2.91503639,  5.58685232, 18.28458445]]])

In [35]:
b / np.std(b, axis=0, keepdims=False)

array([[[ 2.27237699,  6.98291756,  2.98964391,  8.35908982],
        [ 4.41557661,  5.33183809,  6.71940992,  2.50493227],
        [ 1.17219478,  0.91503639,  3.58685232, 16.28458445]],

       [[ 0.27237699,  4.98291756,  0.98964391,  6.35908982],
        [ 2.41557661,  3.33183809,  8.71940992,  0.50493227],
        [ 3.17219478,  2.91503639,  5.58685232, 18.28458445]]])

In [36]:
b / np.std(b, axis=1, keepdims=False)

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4) 