## 사칙연산

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3,4])

In [3]:
b = np.array([2,4,6,8,10])

In [4]:
a + b

array([ 2,  5,  8, 11, 14])

In [5]:
a + 4

array([4, 5, 6, 7, 8])

In [6]:
np.add(a,b)

array([ 2,  5,  8, 11, 14])

In [7]:
np.add(a, 4)

array([4, 5, 6, 7, 8])

In [8]:
a - b

array([-2, -3, -4, -5, -6])

In [9]:
b - a

array([2, 3, 4, 5, 6])

In [10]:
a - 4

array([-4, -3, -2, -1,  0])

In [11]:
a * b

array([ 0,  4, 12, 24, 40])

In [12]:
a * 2

array([0, 2, 4, 6, 8])

In [13]:
b / a

/Users/kobi.kuma/py3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [14]:
b / 2

array([1., 2., 3., 4., 5.])

In [15]:
b / 3

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [16]:
b // 3 

array([0, 1, 2, 2, 3])

In [17]:
b % 3

array([2, 1, 0, 2, 1])

In [18]:
np.mod(b, 3) # 나머지, b%3

array([2, 1, 0, 2, 1])

## power , sqrt 

In [20]:
np.power(a, 2)

array([ 0,  1,  4,  9, 16])

In [21]:
np.power(2, 3)

8

In [22]:
2**3

8

In [23]:
a = np.arange(1, 11, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
b = np.array([1,2,1,2,1,2,1,2,1,2])

In [25]:
np.power(a, b)

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

In [26]:
a ** b

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

In [27]:
np.sqrt(2)

1.4142135623730951

In [28]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

## 삼각함수
* 인수로는 radian를 사용

In [29]:
np.sin(0)

0.0

In [30]:
np.cos(0)

1.0

In [31]:
np.tan(0)

0.0

In [32]:
np.sin(np.pi*0.5)

1.0

In [36]:
np.cos(np.pi*0.5)  # 0에 수렴

6.123233995736766e-17

In [37]:
np.tan(np.pi*0.5)  # 무한

1.633123935319537e+16

In [38]:
np.sin(1)

0.8414709848078965

In [39]:
np.cos(1)

0.5403023058681398

In [40]:
np.tan(1)

1.557407724654902

In [41]:
np.sin(90)

0.8939966636005579

In [42]:
np.sin(180)

-0.8011526357338306

### 역삼각함수

In [44]:
np.arcsin(0.5)

0.5235987755982988

In [45]:
np.arccos(0.5)

1.0471975511965976

In [46]:
np.arctan(1.0)

0.7853981633974483

In [47]:
np.arcsin(-1.0)

-1.5707963267948966

In [48]:
np.arccos(-1.0)

3.141592653589793

In [49]:
np.arctan(-0.5)

-0.46364760900080615

### 라디안

In [50]:
np.radians(120)

2.0943951023931953

In [51]:
np.deg2rad(12)

0.20943951023931956

In [52]:
np.rad2deg(3.14)

179.9087476710785

In [53]:
np.deg2rad(np.rad2deg(2.3))

2.3

In [54]:
%timeit np.radians(24)

938 ns ± 11.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [55]:
%timeit np.deg2rad(24)

949 ns ± 19.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 지수/로그

In [56]:
np.exp(1)

2.718281828459045

In [57]:
np.exp(2)

7.38905609893065

In [58]:
np.exp(0)

1.0

In [59]:
np.log(np.e)

1.0

In [60]:
a = np.array([1., 2., np.e**2, 10])

In [61]:
np.log(a)

array([0.        , 0.69314718, 2.        , 2.30258509])

In [62]:
b = np.array([1., 2., 4., 7.])
b

array([1., 2., 4., 7.])

In [63]:
np.log2(b)

array([0.        , 1.        , 2.        , 2.80735492])

In [64]:
c = np.array([1, 10, 20, 100])
c

array([  1,  10,  20, 100])

In [65]:
np.log10(c)

array([0.     , 1.     , 1.30103, 2.     ])

In [67]:
np.log1p(a)

array([0.69314718, 1.09861229, 2.12692801, 2.39789527])

In [68]:
np.log(2)/np.log(4)

0.5

In [69]:
np.log(9)/np.log(3)

2.0

## 쌍곡선 함수(hyperbolic)

* $\sinh x = \frac { e^x - e^{-x}} {2}$

* $\cosh x = \frac { e^x + e^{-x}} {2}$


* $\tanh x = \frac { \sinh x } { \cosh x}$




In [70]:
np.sinh(2)

3.6268604078470186

In [71]:
np.cosh(2)

3.7621956910836314

In [72]:
np.tanh(2)

0.9640275800758169

In [73]:
np.sinh(-1)

-1.1752011936438014

In [74]:
np.cosh(-1)

1.5430806348152437

In [75]:
np.tanh(-1)

-0.7615941559557649

In [76]:
np.arcsinh(2)

1.4436354751788103

In [77]:
np.arccosh(1)

0.0

In [78]:
np.arctanh(0.7)

0.8673005276940532

## 반올림 내림
* np.floor() / np.trunc() / np.ceil() / np.round() / np.around() / np.rint() / np.fix()

In [80]:
a = np.array([-1.8, -1.4, -1.0, -0.6, -0.2, 0, 0.2, 0.6, 1.0, 1.4, 1.8])

In [81]:
np.floor(a)

array([-2., -2., -1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.])

In [82]:
np.trunc(a)

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [83]:
np.ceil(a)

array([-1., -1., -1., -0., -0.,  0.,  1.,  1.,  1.,  2.,  2.])

In [84]:
np.round(a)

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [85]:
np.around(a)

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [86]:
np.rint(a)

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [88]:
np.fix(a) # 0에 가깝운 방향으로 수렴하도록

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

## 복소수
* np.real()
* np.imag()
* np.conj()

In [89]:
a = 1+2j
a

(1+2j)

In [90]:
b = -2+1j
b

(-2+1j)

In [91]:
np.real(a)

1.0

In [92]:
np.imag(a)

2.0

In [93]:
a+b

(-1+3j)

In [95]:
a*b # (1+2j)*(-2+1j) = -2 + 1j -4j -2 = -4 - 3j

(-4-3j)

In [96]:
a/b

(-0-1j)

In [98]:
np.conj(a) # https://ko.wikipedia.org/wiki/%EC%BC%A4%EB%A0%88_%EB%B3%B5%EC%86%8C%EC%88%98

(1-2j)

## 절대값
* np.fabs, np.absolute,

In [99]:
a = -2.5

In [100]:
np.absolute(a)

2.5

In [101]:
np.abs(a)

2.5

In [102]:
np.fabs(a)

2.5

In [103]:
b = -2 + 3j

In [104]:
np.abs(b)

3.605551275463989

In [113]:
#

In [105]:
np.fabs(b)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [106]:
c = np.array([-1, 2, -8, 12, 1+2j])

In [107]:
np.abs(c)

array([ 1.        ,  2.        ,  8.        , 12.        ,  2.23606798])

## 수학적 상수

In [114]:
np.e

2.718281828459045

In [115]:
np.pi

3.141592653589793