In [1]:
# https://deepage.net/features/numpy-var.html

## 분산
* V
* $V=\frac {1}{N} \sum_{i=0}^{N} {(x-\overline{x})^2}$
* $\overline{x} = average$
```python
numpy.var (a, axis = None, dtype = None, out = None, ddof = 0, keepdims = False)
```

In [2]:
import numpy as np
a = np.array([10, 20, 12, 0, 3, 5])
a

array([10, 20, 12,  0,  3,  5])

In [3]:
np.var(a)

43.55555555555555

In [13]:
np.mean(a)

8.333333333333334

In [20]:
np.sum(np.power(a-np.mean(a),2))/len(a) 

43.55555555555555

In [4]:
b = np.random.randint(20, size=(3,4))
b

array([[12,  4,  9, 12],
       [18,  7, 10, 12],
       [ 8,  0, 18,  3]])

In [5]:
np.var(b)

27.909722222222218

In [6]:
np.var(b, axis=0)

array([16.88888889,  8.22222222, 16.22222222, 18.        ])

In [7]:
np.var(b, axis=1)

array([10.6875, 16.1875, 46.6875])

In [8]:
np.var(b, axis=(0,1))

27.909722222222218

In [9]:
# dtype

In [10]:
c = np.random.randn(100).reshape(5, 20)
c

array([[-0.62770224, -1.17736156,  0.48876144, -1.11459149,  0.77944579,
        -2.27515432,  2.50005569,  0.48912706, -0.41803513, -1.18228615,
        -0.64531645,  0.37962318,  0.15523965,  1.16241031, -0.24654083,
         0.777638  , -0.68096334, -0.26124993, -0.35383814,  1.22068305],
       [-1.64934054,  1.63571331,  0.83148082, -1.46211095, -1.19274215,
         0.58480824, -0.60188567, -0.05656122, -0.01071899,  0.93564999,
         0.00873814, -1.27834768, -1.64736188, -1.2610256 ,  0.71577048,
        -0.77076214, -0.56076312, -1.02909411, -0.66686171, -0.24035598],
       [-1.07659264, -0.6628197 ,  0.68275737,  0.31908789, -2.00246969,
        -0.10626263, -0.86696783, -0.00504463,  0.23062991,  1.64294751,
         0.03972638, -0.87278609,  0.29575756,  0.53412004,  1.09626701,
        -0.50222345,  0.6733984 , -0.88926937,  1.46384363,  0.60158203],
       [ 0.06106847, -1.48772719, -0.67969472,  1.31588528, -0.88191057,
        -1.44335208,  1.79416806,  0.85282867,  

In [11]:
np.var(c, dtype='float32')

0.97173804

In [12]:
np.var(c, dtype='float64')

0.9717380592639893

In [29]:
## ddof (N-ddof) : 샘플수를 ddof수만큼 줄임

In [22]:
d = np.random.randn(10)
d

array([ 1.20819951,  0.1587812 ,  1.1554682 , -1.49492083,  1.77792661,
       -0.23743401,  0.49473426,  0.70412413,  0.05952435,  0.63353928])

In [23]:
np.var(d, ddof=0)

0.7428609586233074

In [24]:
np.var(d, ddof=1)

0.8254010651370082

In [25]:
e = np.random.randn(5)
e

array([-0.05635354,  1.13570193, -2.32753285,  2.32475427,  0.63352562])

In [26]:
np.var(e)

2.386271119608974

In [27]:
np.var(e, ddof=0)

2.386271119608974

In [28]:
np.var(e, ddof=1)

2.9828388995112176

In [30]:
## keepdims

In [31]:
f = np.random.randint(20, size=(2,5,10))
f

array([[[ 8, 19,  5, 12,  0,  6,  8,  4,  9, 16],
        [ 7, 10,  0,  7,  9,  4,  7, 15,  1, 17],
        [ 3,  3, 11, 11, 18,  1, 17, 13, 17, 17],
        [11, 19, 12,  8,  2, 17,  0, 16,  5,  5],
        [ 4,  7,  2,  3, 13,  1, 10,  6, 13, 10]],

       [[13, 19, 12, 11, 10,  2, 12, 11,  1, 11],
        [ 4, 18, 15, 17, 11, 18,  9, 13,  3, 12],
        [15,  6, 18,  2,  1, 17, 18,  9, 10,  1],
        [ 3, 12,  9,  3, 15, 16,  1,  6,  5,  8],
        [15, 18,  8, 10,  0,  8,  7,  3,  4, 17]]])

In [32]:
f_var = np.var(f, axis=1)

In [33]:
f/f_var

ValueError: operands could not be broadcast together with shapes (2,5,10) (2,10) 

In [34]:
f_var.shape, f.shape

((2, 10), (2, 5, 10))

In [35]:
f_var = np.var(f, axis=1, keepdims=True)

In [36]:
f/f_var

array([[[0.97087379, 0.45849421, 0.21929825, 1.18110236, 0.        ,
         0.17162471, 0.26809651, 0.16835017, 0.28125   , 0.70175439],
        [0.84951456, 0.24131274, 0.        , 0.68897638, 0.19982238,
         0.11441648, 0.23458445, 0.63131313, 0.03125   , 0.74561404],
        [0.36407767, 0.07239382, 0.48245614, 1.08267717, 0.39964476,
         0.02860412, 0.56970509, 0.54713805, 0.53125   , 0.74561404],
        [1.33495146, 0.45849421, 0.52631579, 0.78740157, 0.04440497,
         0.48627002, 0.        , 0.67340067, 0.15625   , 0.21929825],
        [0.48543689, 0.16891892, 0.0877193 , 0.29527559, 0.28863233,
         0.02860412, 0.33512064, 0.25252525, 0.40625   , 0.43859649]],

       [[0.45138889, 0.7711039 , 0.86705202, 0.35900783, 0.2886836 ,
         0.05186722, 0.38167939, 0.87025316, 0.11061947, 0.3962536 ],
        [0.13888889, 0.73051948, 1.08381503, 0.55483029, 0.31755196,
         0.46680498, 0.28625954, 1.02848101, 0.33185841, 0.43227666],
        [0.52083333, 0.24

## 평균/편차/분산
http://math7.tistory.com/16

* 4개의 수 : 50,60,70,80
* 평균 : (50+60+70+80)/4 = 65
* 편차 : ((50-65)^2+ ... )/4 = 7.5
* 분산 : 편차 제곱의 평균