In [1]:
# https://deepage.net/features/numpy-average.html

* average와 mean의 차이
* 함수 사용

### average / mean

* http://blog.naver.com/PostView.nhn?blogId=sw4r&logNo=221010499304
* 

In [2]:
import numpy as np

In [3]:
a = np.array([33, 44, 54, 23, 25, 55, 32, 76])
a

array([33, 44, 54, 23, 25, 55, 32, 76])

In [4]:
np.average(a)

42.75

In [5]:
np.sum(a)/len(a)

42.75

In [7]:
a = a.reshape(2,4)
a

array([[33, 44, 54, 23],
       [25, 55, 32, 76]])

In [8]:
np.average(a)

42.75

In [10]:
np.average(a, axis=0) # (33+25)/2

array([29. , 49.5, 43. , 49.5])

In [12]:
np.average(a, axis=1) # (33+44+54+23)/4

array([38.5, 47. ])

In [13]:
b = np.random.rand(24).reshape(2,3,4)

In [14]:
b

array([[[0.30618921, 0.45016715, 0.63844164, 0.78788592],
        [0.24539328, 0.83942214, 0.14646077, 0.50875579],
        [0.37266699, 0.08994618, 0.91139992, 0.29142707]],

       [[0.11421503, 0.80854236, 0.73301165, 0.04174908],
        [0.72736432, 0.0740511 , 0.91726835, 0.79242534],
        [0.01444261, 0.10526063, 0.62084104, 0.12131054]]])

In [18]:
np.average(b, axis=0) # (0.30618921+0.11421503)/2

array([[0.21020212, 0.62935476, 0.68572665, 0.4148175 ],
       [0.4863788 , 0.45673662, 0.53186456, 0.65059056],
       [0.1935548 , 0.0976034 , 0.76612048, 0.2063688 ]])

In [19]:
np.average(b, axis=1) #(0.30618921+0.24539328+0.37266699)/3

array([[0.30808316, 0.45984516, 0.56543411, 0.52935626],
       [0.28534065, 0.3292847 , 0.75704035, 0.31849499]])

In [20]:
np.average(b, axis=2) # (0.30618921, 0.45016715, 0.63844164, 0.78788592)/4

array([[0.54567098, 0.435008  , 0.41636004],
       [0.42437953, 0.62777728, 0.21546371]])

In [21]:
# weight

In [24]:
a = a.flatten()
a, a.shape

(array([33, 44, 54, 23, 25, 55, 32, 76]), (8,))

In [25]:
w = np.array([0.1, 0.05, 0.2, 0.0, 0.0, 0.4, 0.2, 0.05])
w, w.shape

(array([0.1 , 0.05, 0.2 , 0.  , 0.  , 0.4 , 0.2 , 0.05]), (8,))

In [26]:
np.average(a, weights=w)

48.5

In [29]:
np.sum(a*w)

48.5

In [30]:
w2 = np.array([0.2, 0.8])

In [31]:
a = a.reshape(2, 4)
a

array([[33, 44, 54, 23],
       [25, 55, 32, 76]])

In [33]:
np.average(a, axis=0, weights=w2)

array([26.6, 52.8, 36.4, 65.4])

In [35]:
np.sum(np.array([33, 25])*w2)

26.6

In [36]:
np.average(a, returned="True")

(42.75, 8.0)

In [37]:
a = a.flatten()
a

array([33, 44, 54, 23, 25, 55, 32, 76])

In [38]:
w

array([0.1 , 0.05, 0.2 , 0.  , 0.  , 0.4 , 0.2 , 0.05])

In [40]:
r = np.average(a, weights=w, returned="True")

In [41]:
r

(48.5, 1.0)

In [42]:
type(r)

tuple

In [48]:
r = np.average(a, weights=w)


In [50]:
r, type(r)

(48.5, numpy.float64)

## np.mean 
* np.average와는 다르게 weight을 이용할 수 없음

In [51]:
a = np.random.randint(0, 10, 20)
a

array([6, 3, 1, 8, 6, 4, 3, 7, 7, 9, 2, 4, 6, 4, 2, 7, 8, 5, 9, 3])

In [52]:
np.mean(a)

5.2

In [53]:
b = a.reshape(4, 5)
b

array([[6, 3, 1, 8, 6],
       [4, 3, 7, 7, 9],
       [2, 4, 6, 4, 2],
       [7, 8, 5, 9, 3]])

In [54]:
np.mean(b)

5.2

In [55]:
np.mean(b, axis=0)

array([4.75, 4.5 , 4.75, 7.  , 5.  ])

In [57]:
np.sum([6,4,2,7])/4

4.75

In [56]:
np.mean(b, axis=1)

array([4.8, 6. , 3.6, 6.4])

In [58]:
np.sum([6, 3, 1, 8, 6])/5

4.8

In [59]:
c = np.random.rand(24).reshape((2,3,4))
c

array([[[0.85994038, 0.36724365, 0.81487273, 0.03679824],
        [0.8963545 , 0.40869898, 0.29383096, 0.90986784],
        [0.43281219, 0.21070356, 0.90360322, 0.03803603]],

       [[0.48871215, 0.03587417, 0.7192912 , 0.42121834],
        [0.68160167, 0.05778946, 0.78115168, 0.44316494],
        [0.87875556, 0.84189448, 0.42874879, 0.05969657]]])

In [60]:
np.mean(c)

0.5004442205243494

In [61]:
np.mean(c, axis=0)

array([[0.67432626, 0.20155891, 0.76708196, 0.22900829],
       [0.78897808, 0.23324422, 0.53749132, 0.67651639],
       [0.65578387, 0.52629902, 0.66617601, 0.0488663 ]])

In [62]:
np.mean(c, axis=1)

array([[0.72970236, 0.32888207, 0.67076897, 0.32823404],
       [0.68302313, 0.3118527 , 0.64306389, 0.30802662]])

In [63]:
np.mean(c, axis=2)

array([[0.51971375, 0.62718807, 0.39628875],
       [0.41627396, 0.49092694, 0.55227385]])

In [66]:
d = np.random.rand(1000)

In [67]:
d.dtype

dtype('float64')

In [68]:
np.mean(d)

0.49648141173701826

In [69]:
np.mean(d, dtype="float32")

0.4964814

In [70]:
np.mean(d, dtype="float16")

0.4966

In [71]:
## keepdims

In [72]:
b

array([[6, 3, 1, 8, 6],
       [4, 3, 7, 7, 9],
       [2, 4, 6, 4, 2],
       [7, 8, 5, 9, 3]])

In [73]:
e = np.mean(b, keepdims=True)
e

array([[5.2]])

In [74]:
f = np.mean(b, keepdims=False)
f

5.2

In [77]:
g = np.mean(b, axis=1, keepdims=True)
g

array([[4.8],
       [6. ],
       [3.6],
       [6.4]])

In [78]:
g.shape

(4, 1)

In [79]:
h = np.mean(b, axis=1, keepdims=False)
h

array([4.8, 6. , 3.6, 6.4])

In [80]:
h.shape

(4,)