In [1]:
#https://deepage.net/features/numpy-sum.html

```
numpy.sum (a, axis = None, dtype = None, out = None, keepdims = None)
```


In [2]:
import numpy as np

In [3]:
a = np.random.randint(0, 10, size=(2, 5))
a

array([[5, 4, 8, 4, 2],
       [1, 8, 4, 8, 7]])

In [4]:
np.sum(a)

51

In [5]:
b = np.array([2, 4, 1, 6])

In [6]:
b

array([2, 4, 1, 6])

In [7]:
np.sum(b)

13

In [8]:
c = np.random.randint(0, 10, size=(2,4,5))
c

array([[[7, 3, 1, 9, 3],
        [3, 6, 4, 1, 5],
        [3, 2, 7, 5, 2],
        [9, 1, 5, 9, 3]],

       [[9, 5, 4, 7, 5],
        [1, 6, 8, 4, 5],
        [6, 3, 6, 5, 5],
        [4, 9, 7, 0, 8]]])

In [9]:
np.sum(c)

195

In [10]:
## axis

In [11]:
a

array([[5, 4, 8, 4, 2],
       [1, 8, 4, 8, 7]])

In [12]:
np.sum(a, axis=0)

array([ 6, 12, 12, 12,  9])

In [13]:
np.sum(a, axis=1)

array([23, 28])

In [14]:
c

array([[[7, 3, 1, 9, 3],
        [3, 6, 4, 1, 5],
        [3, 2, 7, 5, 2],
        [9, 1, 5, 9, 3]],

       [[9, 5, 4, 7, 5],
        [1, 6, 8, 4, 5],
        [6, 3, 6, 5, 5],
        [4, 9, 7, 0, 8]]])

In [15]:
np.sum(c, axis=0)

array([[16,  8,  5, 16,  8],
       [ 4, 12, 12,  5, 10],
       [ 9,  5, 13, 10,  7],
       [13, 10, 12,  9, 11]])

In [16]:
np.sum(c, axis=1)

array([[22, 12, 17, 24, 13],
       [20, 23, 25, 16, 23]])

In [17]:
np.sum(c, axis=2)

array([[23, 19, 19, 27],
       [30, 24, 25, 28]])

In [18]:
## keepsdim

In [19]:
np.sum(c, axis=0, keepdims=True)

array([[[16,  8,  5, 16,  8],
        [ 4, 12, 12,  5, 10],
        [ 9,  5, 13, 10,  7],
        [13, 10, 12,  9, 11]]])

In [20]:
np.sum(c, axis=1, keepdims=True)

array([[[22, 12, 17, 24, 13]],

       [[20, 23, 25, 16, 23]]])

In [21]:
np.sum(c, axis=2, keepdims=True)

array([[[23],
        [19],
        [19],
        [27]],

       [[30],
        [24],
        [25],
        [28]]])

In [22]:
np.sum(a, dtype='int8')

51

In [23]:
np.sum(a, axis=0, dtype='float')

array([ 6., 12., 12., 12.,  9.])

In [24]:
## numpy.ndarray.sum

In [25]:
a

array([[5, 4, 8, 4, 2],
       [1, 8, 4, 8, 7]])

In [26]:
b

array([2, 4, 1, 6])

In [27]:
c

array([[[7, 3, 1, 9, 3],
        [3, 6, 4, 1, 5],
        [3, 2, 7, 5, 2],
        [9, 1, 5, 9, 3]],

       [[9, 5, 4, 7, 5],
        [1, 6, 8, 4, 5],
        [6, 3, 6, 5, 5],
        [4, 9, 7, 0, 8]]])

In [28]:
a.sum()

51

In [29]:
b.sum()

13

In [30]:
c.sum()

195

In [31]:
a.sum(axis=0)

array([ 6, 12, 12, 12,  9])

In [32]:
c.sum(axis=0)

array([[16,  8,  5, 16,  8],
       [ 4, 12, 12,  5, 10],
       [ 9,  5, 13, 10,  7],
       [13, 10, 12,  9, 11]])

In [33]:
c.sum(axis=2)

array([[23, 19, 19, 27],
       [30, 24, 25, 28]])

In [34]:
c.sum(axis=2, keepdims=True)

array([[[23],
        [19],
        [19],
        [27]],

       [[30],
        [24],
        [25],
        [28]]])

In [35]:
a.sum(axis=0, dtype='float')

array([ 6., 12., 12., 12.,  9.])