In [1]:
# https://deepage.net/features/numpy-median.html

## 중간값

$(a_1, a_2, ..., a_n, a_{n+1}, ... , a_{2n})$
* 중앙값 = $ \frac {a_n + a_{n+1}} {2}$

$(a_1, a_2, ..., a_n, a_{n+1}, ... , a_{2n-1})$
* 중앙값 = $ a_n $

### np.median()

``` python
numpy.median (a, axis = None, out = None, overwrite_input = False, keepdims = False)
```




In [2]:
import numpy as np


In [3]:
a = np.random.randint(100, size=(2,3,4))
a

array([[[27, 73, 46, 92],
        [21, 88, 92, 40],
        [92, 91, 62,  2]],

       [[32, 71, 51, 73],
        [59, 61, 53, 79],
        [57, 92,  0, 19]]])

In [4]:
np.median(a)

60.0

In [9]:
np.sort(a.flatten())

array([ 0,  2, 19, 21, 27, 32, 40, 46, 51, 53, 57, 59, 61, 62, 71, 73, 73,
       79, 88, 91, 92, 92, 92, 92])

In [10]:
np.median(a, axis=2)

array([[59.5, 64. , 76.5],
       [61. , 60. , 38. ]])

In [12]:
np.median(a, axis=1)

array([[27., 88., 62., 40.],
       [57., 71., 51., 73.]])

In [11]:
np.median(a, axis=(1,2))

array([67.5, 58. ])

In [13]:
b = a.copy()
b

array([[[27, 73, 46, 92],
        [21, 88, 92, 40],
        [92, 91, 62,  2]],

       [[32, 71, 51, 73],
        [59, 61, 53, 79],
        [57, 92,  0, 19]]])

In [14]:
np.median(b, axis=1, overwrite_input=True)

array([[27., 88., 62., 40.],
       [57., 71., 51., 73.]])

In [16]:
np.all(a==b)

False

In [17]:
a

array([[[27, 73, 46, 92],
        [21, 88, 92, 40],
        [92, 91, 62,  2]],

       [[32, 71, 51, 73],
        [59, 61, 53, 79],
        [57, 92,  0, 19]]])

In [18]:
b

array([[[21, 73, 46,  2],
        [27, 88, 62, 40],
        [92, 91, 92, 92]],

       [[32, 61,  0, 19],
        [57, 71, 51, 73],
        [59, 92, 53, 79]]])

In [19]:
np.median(a, axis=0, keepdims=False)

array([[29.5, 72. , 48.5, 82.5],
       [40. , 74.5, 72.5, 59.5],
       [74.5, 91.5, 31. , 10.5]])

In [20]:
np.median(a, axis=0, keepdims=True)

array([[[29.5, 72. , 48.5, 82.5],
        [40. , 74.5, 72.5, 59.5],
        [74.5, 91.5, 31. , 10.5]]])

In [21]:
np.median(a, axis=1, keepdims=False)

array([[27., 88., 62., 40.],
       [57., 71., 51., 73.]])

In [22]:
np.median(a, axis=1, keepdims=True)

array([[[27., 88., 62., 40.]],

       [[57., 71., 51., 73.]]])

In [23]:
np.median(a, axis=(0,2), keepdims=True)

array([[[61. ],
        [60. ],
        [59.5]]])